# This file is auto-generated by scripts/compile_models.py

import os
import site
import sysconfig

_RELATIVE_BLOB_FOLDER = os.path.join("oakutils", "blobs", "models")
_SITE_SITE_PACKAGES = site.getusersitepackages()
_SYSCONFIG_SITE_PACKAGES = sysconfig.get_paths()["purelib"]
_SITE_PACKAGES = _SITE_SITE_PACKAGES if os.name == "posix" else _SYSCONFIG_SITE_PACKAGES
_BLOB_FOLDER = os.path.join(_SITE_PACKAGES, _RELATIVE_BLOB_FOLDER)

GAUSSIANGRAY_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "GaussianGray_11x11.blob")
)
GAUSSIANGRAY_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "GaussianGray_13x13.blob")
)
GAUSSIANGRAY_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "GaussianGray_15x15.blob")
)
GAUSSIANGRAY_3X3 = os.path.abspath(os.path.join(_BLOB_FOLDER, "GaussianGray_3x3.blob"))
GAUSSIANGRAY_5X5 = os.path.abspath(os.path.join(_BLOB_FOLDER, "GaussianGray_5x5.blob"))
GAUSSIANGRAY_7X7 = os.path.abspath(os.path.join(_BLOB_FOLDER, "GaussianGray_7x7.blob"))
GAUSSIANGRAY_9X9 = os.path.abspath(os.path.join(_BLOB_FOLDER, "GaussianGray_9x9.blob"))
GAUSSIAN_11X11 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Gaussian_11x11.blob"))
GAUSSIAN_13X13 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Gaussian_13x13.blob"))
GAUSSIAN_15X15 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Gaussian_15x15.blob"))
GAUSSIAN_3X3 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Gaussian_3x3.blob"))
GAUSSIAN_5X5 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Gaussian_5x5.blob"))
GAUSSIAN_7X7 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Gaussian_7x7.blob"))
GAUSSIAN_9X9 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Gaussian_9x9.blob"))
LAPLACIANBLURGRAY_11X11_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_11x11_11x11.blob")
)
LAPLACIANBLURGRAY_11X11_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_11x11_13x13.blob")
)
LAPLACIANBLURGRAY_11X11_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_11x11_15x15.blob")
)
LAPLACIANBLURGRAY_11X11_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_11x11_3x3.blob")
)
LAPLACIANBLURGRAY_11X11_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_11x11_5x5.blob")
)
LAPLACIANBLURGRAY_11X11_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_11x11_7x7.blob")
)
LAPLACIANBLURGRAY_11X11_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_11x11_9x9.blob")
)
LAPLACIANBLURGRAY_13X13_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_13x13_11x11.blob")
)
LAPLACIANBLURGRAY_13X13_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_13x13_13x13.blob")
)
LAPLACIANBLURGRAY_13X13_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_13x13_15x15.blob")
)
LAPLACIANBLURGRAY_13X13_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_13x13_3x3.blob")
)
LAPLACIANBLURGRAY_13X13_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_13x13_5x5.blob")
)
LAPLACIANBLURGRAY_13X13_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_13x13_7x7.blob")
)
LAPLACIANBLURGRAY_13X13_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_13x13_9x9.blob")
)
LAPLACIANBLURGRAY_15X15_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_15x15_11x11.blob")
)
LAPLACIANBLURGRAY_15X15_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_15x15_13x13.blob")
)
LAPLACIANBLURGRAY_15X15_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_15x15_15x15.blob")
)
LAPLACIANBLURGRAY_15X15_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_15x15_3x3.blob")
)
LAPLACIANBLURGRAY_15X15_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_15x15_5x5.blob")
)
LAPLACIANBLURGRAY_15X15_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_15x15_7x7.blob")
)
LAPLACIANBLURGRAY_15X15_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_15x15_9x9.blob")
)
LAPLACIANBLURGRAY_3X3_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_3x3_11x11.blob")
)
LAPLACIANBLURGRAY_3X3_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_3x3_13x13.blob")
)
LAPLACIANBLURGRAY_3X3_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_3x3_15x15.blob")
)
LAPLACIANBLURGRAY_3X3_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_3x3_3x3.blob")
)
LAPLACIANBLURGRAY_3X3_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_3x3_5x5.blob")
)
LAPLACIANBLURGRAY_3X3_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_3x3_7x7.blob")
)
LAPLACIANBLURGRAY_3X3_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_3x3_9x9.blob")
)
LAPLACIANBLURGRAY_5X5_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_5x5_11x11.blob")
)
LAPLACIANBLURGRAY_5X5_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_5x5_13x13.blob")
)
LAPLACIANBLURGRAY_5X5_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_5x5_15x15.blob")
)
LAPLACIANBLURGRAY_5X5_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_5x5_3x3.blob")
)
LAPLACIANBLURGRAY_5X5_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_5x5_5x5.blob")
)
LAPLACIANBLURGRAY_5X5_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_5x5_7x7.blob")
)
LAPLACIANBLURGRAY_5X5_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_5x5_9x9.blob")
)
LAPLACIANBLURGRAY_7X7_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_7x7_11x11.blob")
)
LAPLACIANBLURGRAY_7X7_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_7x7_13x13.blob")
)
LAPLACIANBLURGRAY_7X7_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_7x7_15x15.blob")
)
LAPLACIANBLURGRAY_7X7_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_7x7_3x3.blob")
)
LAPLACIANBLURGRAY_7X7_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_7x7_5x5.blob")
)
LAPLACIANBLURGRAY_7X7_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_7x7_7x7.blob")
)
LAPLACIANBLURGRAY_7X7_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_7x7_9x9.blob")
)
LAPLACIANBLURGRAY_9X9_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_9x9_11x11.blob")
)
LAPLACIANBLURGRAY_9X9_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_9x9_13x13.blob")
)
LAPLACIANBLURGRAY_9X9_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_9x9_15x15.blob")
)
LAPLACIANBLURGRAY_9X9_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_9x9_3x3.blob")
)
LAPLACIANBLURGRAY_9X9_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_9x9_5x5.blob")
)
LAPLACIANBLURGRAY_9X9_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_9x9_7x7.blob")
)
LAPLACIANBLURGRAY_9X9_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlurGray_9x9_9x9.blob")
)
LAPLACIANBLUR_11X11_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_11x11_11x11.blob")
)
LAPLACIANBLUR_11X11_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_11x11_13x13.blob")
)
LAPLACIANBLUR_11X11_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_11x11_15x15.blob")
)
LAPLACIANBLUR_11X11_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_11x11_3x3.blob")
)
LAPLACIANBLUR_11X11_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_11x11_5x5.blob")
)
LAPLACIANBLUR_11X11_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_11x11_7x7.blob")
)
LAPLACIANBLUR_11X11_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_11x11_9x9.blob")
)
LAPLACIANBLUR_13X13_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_13x13_11x11.blob")
)
LAPLACIANBLUR_13X13_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_13x13_13x13.blob")
)
LAPLACIANBLUR_13X13_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_13x13_15x15.blob")
)
LAPLACIANBLUR_13X13_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_13x13_3x3.blob")
)
LAPLACIANBLUR_13X13_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_13x13_5x5.blob")
)
LAPLACIANBLUR_13X13_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_13x13_7x7.blob")
)
LAPLACIANBLUR_13X13_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_13x13_9x9.blob")
)
LAPLACIANBLUR_15X15_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_15x15_11x11.blob")
)
LAPLACIANBLUR_15X15_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_15x15_13x13.blob")
)
LAPLACIANBLUR_15X15_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_15x15_15x15.blob")
)
LAPLACIANBLUR_15X15_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_15x15_3x3.blob")
)
LAPLACIANBLUR_15X15_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_15x15_5x5.blob")
)
LAPLACIANBLUR_15X15_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_15x15_7x7.blob")
)
LAPLACIANBLUR_15X15_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_15x15_9x9.blob")
)
LAPLACIANBLUR_3X3_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_3x3_11x11.blob")
)
LAPLACIANBLUR_3X3_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_3x3_13x13.blob")
)
LAPLACIANBLUR_3X3_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_3x3_15x15.blob")
)
LAPLACIANBLUR_3X3_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_3x3_3x3.blob")
)
LAPLACIANBLUR_3X3_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_3x3_5x5.blob")
)
LAPLACIANBLUR_3X3_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_3x3_7x7.blob")
)
LAPLACIANBLUR_3X3_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_3x3_9x9.blob")
)
LAPLACIANBLUR_5X5_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_5x5_11x11.blob")
)
LAPLACIANBLUR_5X5_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_5x5_13x13.blob")
)
LAPLACIANBLUR_5X5_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_5x5_15x15.blob")
)
LAPLACIANBLUR_5X5_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_5x5_3x3.blob")
)
LAPLACIANBLUR_5X5_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_5x5_5x5.blob")
)
LAPLACIANBLUR_5X5_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_5x5_7x7.blob")
)
LAPLACIANBLUR_5X5_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_5x5_9x9.blob")
)
LAPLACIANBLUR_7X7_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_7x7_11x11.blob")
)
LAPLACIANBLUR_7X7_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_7x7_13x13.blob")
)
LAPLACIANBLUR_7X7_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_7x7_15x15.blob")
)
LAPLACIANBLUR_7X7_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_7x7_3x3.blob")
)
LAPLACIANBLUR_7X7_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_7x7_5x5.blob")
)
LAPLACIANBLUR_7X7_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_7x7_7x7.blob")
)
LAPLACIANBLUR_7X7_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_7x7_9x9.blob")
)
LAPLACIANBLUR_9X9_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_9x9_11x11.blob")
)
LAPLACIANBLUR_9X9_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_9x9_13x13.blob")
)
LAPLACIANBLUR_9X9_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_9x9_15x15.blob")
)
LAPLACIANBLUR_9X9_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_9x9_3x3.blob")
)
LAPLACIANBLUR_9X9_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_9x9_5x5.blob")
)
LAPLACIANBLUR_9X9_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_9x9_7x7.blob")
)
LAPLACIANBLUR_9X9_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianBlur_9x9_9x9.blob")
)
LAPLACIANGRAY_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianGray_11x11.blob")
)
LAPLACIANGRAY_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianGray_13x13.blob")
)
LAPLACIANGRAY_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianGray_15x15.blob")
)
LAPLACIANGRAY_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianGray_3x3.blob")
)
LAPLACIANGRAY_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianGray_5x5.blob")
)
LAPLACIANGRAY_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianGray_7x7.blob")
)
LAPLACIANGRAY_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "LaplacianGray_9x9.blob")
)
LAPLACIAN_11X11 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Laplacian_11x11.blob"))
LAPLACIAN_13X13 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Laplacian_13x13.blob"))
LAPLACIAN_15X15 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Laplacian_15x15.blob"))
LAPLACIAN_3X3 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Laplacian_3x3.blob"))
LAPLACIAN_5X5 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Laplacian_5x5.blob"))
LAPLACIAN_7X7 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Laplacian_7x7.blob"))
LAPLACIAN_9X9 = os.path.abspath(os.path.join(_BLOB_FOLDER, "Laplacian_9x9.blob"))
POINTCLOUD = os.path.abspath(os.path.join(_BLOB_FOLDER, "PointCloud.blob"))
SOBEL = os.path.abspath(os.path.join(_BLOB_FOLDER, "Sobel.blob"))
SOBELBLURGRAY_11X11 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "SobelBlurGray_11x11.blob")
)
SOBELBLURGRAY_13X13 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "SobelBlurGray_13x13.blob")
)
SOBELBLURGRAY_15X15 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "SobelBlurGray_15x15.blob")
)
SOBELBLURGRAY_3X3 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "SobelBlurGray_3x3.blob")
)
SOBELBLURGRAY_5X5 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "SobelBlurGray_5x5.blob")
)
SOBELBLURGRAY_7X7 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "SobelBlurGray_7x7.blob")
)
SOBELBLURGRAY_9X9 = os.path.abspath(
    os.path.join(_BLOB_FOLDER, "SobelBlurGray_9x9.blob")
)
SOBELBLUR_11X11 = os.path.abspath(os.path.join(_BLOB_FOLDER, "SobelBlur_11x11.blob"))
SOBELBLUR_13X13 = os.path.abspath(os.path.join(_BLOB_FOLDER, "SobelBlur_13x13.blob"))
SOBELBLUR_15X15 = os.path.abspath(os.path.join(_BLOB_FOLDER, "SobelBlur_15x15.blob"))
SOBELBLUR_3X3 = os.path.abspath(os.path.join(_BLOB_FOLDER, "SobelBlur_3x3.blob"))
SOBELBLUR_5X5 = os.path.abspath(os.path.join(_BLOB_FOLDER, "SobelBlur_5x5.blob"))
SOBELBLUR_7X7 = os.path.abspath(os.path.join(_BLOB_FOLDER, "SobelBlur_7x7.blob"))
SOBELBLUR_9X9 = os.path.abspath(os.path.join(_BLOB_FOLDER, "SobelBlur_9x9.blob"))
SOBELGRAY = os.path.abspath(os.path.join(_BLOB_FOLDER, "SobelGray.blob"))

"""
Note
-----
This module is auto-generated
Attributes
----------
GAUSSIANGRAY_11X11 : str
    Absolute file path for GAUSSIANGRAY_11X11 file
GAUSSIANGRAY_13X13 : str
    Absolute file path for GAUSSIANGRAY_13X13 file
GAUSSIANGRAY_15X15 : str
    Absolute file path for GAUSSIANGRAY_15X15 file
GAUSSIANGRAY_3X3 : str
    Absolute file path for GAUSSIANGRAY_3X3 file
GAUSSIANGRAY_5X5 : str
    Absolute file path for GAUSSIANGRAY_5X5 file
GAUSSIANGRAY_7X7 : str
    Absolute file path for GAUSSIANGRAY_7X7 file
GAUSSIANGRAY_9X9 : str
    Absolute file path for GAUSSIANGRAY_9X9 file
GAUSSIAN_11X11 : str
    Absolute file path for GAUSSIAN_11X11 file
GAUSSIAN_13X13 : str
    Absolute file path for GAUSSIAN_13X13 file
GAUSSIAN_15X15 : str
    Absolute file path for GAUSSIAN_15X15 file
GAUSSIAN_3X3 : str
    Absolute file path for GAUSSIAN_3X3 file
GAUSSIAN_5X5 : str
    Absolute file path for GAUSSIAN_5X5 file
GAUSSIAN_7X7 : str
    Absolute file path for GAUSSIAN_7X7 file
GAUSSIAN_9X9 : str
    Absolute file path for GAUSSIAN_9X9 file
LAPLACIANBLURGRAY_11X11_11X11 : str
    Absolute file path for LAPLACIANBLURGRAY_11X11_11X11 file
LAPLACIANBLURGRAY_11X11_13X13 : str
    Absolute file path for LAPLACIANBLURGRAY_11X11_13X13 file
LAPLACIANBLURGRAY_11X11_15X15 : str
    Absolute file path for LAPLACIANBLURGRAY_11X11_15X15 file
LAPLACIANBLURGRAY_11X11_3X3 : str
    Absolute file path for LAPLACIANBLURGRAY_11X11_3X3 file
LAPLACIANBLURGRAY_11X11_5X5 : str
    Absolute file path for LAPLACIANBLURGRAY_11X11_5X5 file
LAPLACIANBLURGRAY_11X11_7X7 : str
    Absolute file path for LAPLACIANBLURGRAY_11X11_7X7 file
LAPLACIANBLURGRAY_11X11_9X9 : str
    Absolute file path for LAPLACIANBLURGRAY_11X11_9X9 file
LAPLACIANBLURGRAY_13X13_11X11 : str
    Absolute file path for LAPLACIANBLURGRAY_13X13_11X11 file
LAPLACIANBLURGRAY_13X13_13X13 : str
    Absolute file path for LAPLACIANBLURGRAY_13X13_13X13 file
LAPLACIANBLURGRAY_13X13_15X15 : str
    Absolute file path for LAPLACIANBLURGRAY_13X13_15X15 file
LAPLACIANBLURGRAY_13X13_3X3 : str
    Absolute file path for LAPLACIANBLURGRAY_13X13_3X3 file
LAPLACIANBLURGRAY_13X13_5X5 : str
    Absolute file path for LAPLACIANBLURGRAY_13X13_5X5 file
LAPLACIANBLURGRAY_13X13_7X7 : str
    Absolute file path for LAPLACIANBLURGRAY_13X13_7X7 file
LAPLACIANBLURGRAY_13X13_9X9 : str
    Absolute file path for LAPLACIANBLURGRAY_13X13_9X9 file
LAPLACIANBLURGRAY_15X15_11X11 : str
    Absolute file path for LAPLACIANBLURGRAY_15X15_11X11 file
LAPLACIANBLURGRAY_15X15_13X13 : str
    Absolute file path for LAPLACIANBLURGRAY_15X15_13X13 file
LAPLACIANBLURGRAY_15X15_15X15 : str
    Absolute file path for LAPLACIANBLURGRAY_15X15_15X15 file
LAPLACIANBLURGRAY_15X15_3X3 : str
    Absolute file path for LAPLACIANBLURGRAY_15X15_3X3 file
LAPLACIANBLURGRAY_15X15_5X5 : str
    Absolute file path for LAPLACIANBLURGRAY_15X15_5X5 file
LAPLACIANBLURGRAY_15X15_7X7 : str
    Absolute file path for LAPLACIANBLURGRAY_15X15_7X7 file
LAPLACIANBLURGRAY_15X15_9X9 : str
    Absolute file path for LAPLACIANBLURGRAY_15X15_9X9 file
LAPLACIANBLURGRAY_3X3_11X11 : str
    Absolute file path for LAPLACIANBLURGRAY_3X3_11X11 file
LAPLACIANBLURGRAY_3X3_13X13 : str
    Absolute file path for LAPLACIANBLURGRAY_3X3_13X13 file
LAPLACIANBLURGRAY_3X3_15X15 : str
    Absolute file path for LAPLACIANBLURGRAY_3X3_15X15 file
LAPLACIANBLURGRAY_3X3_3X3 : str
    Absolute file path for LAPLACIANBLURGRAY_3X3_3X3 file
LAPLACIANBLURGRAY_3X3_5X5 : str
    Absolute file path for LAPLACIANBLURGRAY_3X3_5X5 file
LAPLACIANBLURGRAY_3X3_7X7 : str
    Absolute file path for LAPLACIANBLURGRAY_3X3_7X7 file
LAPLACIANBLURGRAY_3X3_9X9 : str
    Absolute file path for LAPLACIANBLURGRAY_3X3_9X9 file
LAPLACIANBLURGRAY_5X5_11X11 : str
    Absolute file path for LAPLACIANBLURGRAY_5X5_11X11 file
LAPLACIANBLURGRAY_5X5_13X13 : str
    Absolute file path for LAPLACIANBLURGRAY_5X5_13X13 file
LAPLACIANBLURGRAY_5X5_15X15 : str
    Absolute file path for LAPLACIANBLURGRAY_5X5_15X15 file
LAPLACIANBLURGRAY_5X5_3X3 : str
    Absolute file path for LAPLACIANBLURGRAY_5X5_3X3 file
LAPLACIANBLURGRAY_5X5_5X5 : str
    Absolute file path for LAPLACIANBLURGRAY_5X5_5X5 file
LAPLACIANBLURGRAY_5X5_7X7 : str
    Absolute file path for LAPLACIANBLURGRAY_5X5_7X7 file
LAPLACIANBLURGRAY_5X5_9X9 : str
    Absolute file path for LAPLACIANBLURGRAY_5X5_9X9 file
LAPLACIANBLURGRAY_7X7_11X11 : str
    Absolute file path for LAPLACIANBLURGRAY_7X7_11X11 file
LAPLACIANBLURGRAY_7X7_13X13 : str
    Absolute file path for LAPLACIANBLURGRAY_7X7_13X13 file
LAPLACIANBLURGRAY_7X7_15X15 : str
    Absolute file path for LAPLACIANBLURGRAY_7X7_15X15 file
LAPLACIANBLURGRAY_7X7_3X3 : str
    Absolute file path for LAPLACIANBLURGRAY_7X7_3X3 file
LAPLACIANBLURGRAY_7X7_5X5 : str
    Absolute file path for LAPLACIANBLURGRAY_7X7_5X5 file
LAPLACIANBLURGRAY_7X7_7X7 : str
    Absolute file path for LAPLACIANBLURGRAY_7X7_7X7 file
LAPLACIANBLURGRAY_7X7_9X9 : str
    Absolute file path for LAPLACIANBLURGRAY_7X7_9X9 file
LAPLACIANBLURGRAY_9X9_11X11 : str
    Absolute file path for LAPLACIANBLURGRAY_9X9_11X11 file
LAPLACIANBLURGRAY_9X9_13X13 : str
    Absolute file path for LAPLACIANBLURGRAY_9X9_13X13 file
LAPLACIANBLURGRAY_9X9_15X15 : str
    Absolute file path for LAPLACIANBLURGRAY_9X9_15X15 file
LAPLACIANBLURGRAY_9X9_3X3 : str
    Absolute file path for LAPLACIANBLURGRAY_9X9_3X3 file
LAPLACIANBLURGRAY_9X9_5X5 : str
    Absolute file path for LAPLACIANBLURGRAY_9X9_5X5 file
LAPLACIANBLURGRAY_9X9_7X7 : str
    Absolute file path for LAPLACIANBLURGRAY_9X9_7X7 file
LAPLACIANBLURGRAY_9X9_9X9 : str
    Absolute file path for LAPLACIANBLURGRAY_9X9_9X9 file
LAPLACIANBLUR_11X11_11X11 : str
    Absolute file path for LAPLACIANBLUR_11X11_11X11 file
LAPLACIANBLUR_11X11_13X13 : str
    Absolute file path for LAPLACIANBLUR_11X11_13X13 file
LAPLACIANBLUR_11X11_15X15 : str
    Absolute file path for LAPLACIANBLUR_11X11_15X15 file
LAPLACIANBLUR_11X11_3X3 : str
    Absolute file path for LAPLACIANBLUR_11X11_3X3 file
LAPLACIANBLUR_11X11_5X5 : str
    Absolute file path for LAPLACIANBLUR_11X11_5X5 file
LAPLACIANBLUR_11X11_7X7 : str
    Absolute file path for LAPLACIANBLUR_11X11_7X7 file
LAPLACIANBLUR_11X11_9X9 : str
    Absolute file path for LAPLACIANBLUR_11X11_9X9 file
LAPLACIANBLUR_13X13_11X11 : str
    Absolute file path for LAPLACIANBLUR_13X13_11X11 file
LAPLACIANBLUR_13X13_13X13 : str
    Absolute file path for LAPLACIANBLUR_13X13_13X13 file
LAPLACIANBLUR_13X13_15X15 : str
    Absolute file path for LAPLACIANBLUR_13X13_15X15 file
LAPLACIANBLUR_13X13_3X3 : str
    Absolute file path for LAPLACIANBLUR_13X13_3X3 file
LAPLACIANBLUR_13X13_5X5 : str
    Absolute file path for LAPLACIANBLUR_13X13_5X5 file
LAPLACIANBLUR_13X13_7X7 : str
    Absolute file path for LAPLACIANBLUR_13X13_7X7 file
LAPLACIANBLUR_13X13_9X9 : str
    Absolute file path for LAPLACIANBLUR_13X13_9X9 file
LAPLACIANBLUR_15X15_11X11 : str
    Absolute file path for LAPLACIANBLUR_15X15_11X11 file
LAPLACIANBLUR_15X15_13X13 : str
    Absolute file path for LAPLACIANBLUR_15X15_13X13 file
LAPLACIANBLUR_15X15_15X15 : str
    Absolute file path for LAPLACIANBLUR_15X15_15X15 file
LAPLACIANBLUR_15X15_3X3 : str
    Absolute file path for LAPLACIANBLUR_15X15_3X3 file
LAPLACIANBLUR_15X15_5X5 : str
    Absolute file path for LAPLACIANBLUR_15X15_5X5 file
LAPLACIANBLUR_15X15_7X7 : str
    Absolute file path for LAPLACIANBLUR_15X15_7X7 file
LAPLACIANBLUR_15X15_9X9 : str
    Absolute file path for LAPLACIANBLUR_15X15_9X9 file
LAPLACIANBLUR_3X3_11X11 : str
    Absolute file path for LAPLACIANBLUR_3X3_11X11 file
LAPLACIANBLUR_3X3_13X13 : str
    Absolute file path for LAPLACIANBLUR_3X3_13X13 file
LAPLACIANBLUR_3X3_15X15 : str
    Absolute file path for LAPLACIANBLUR_3X3_15X15 file
LAPLACIANBLUR_3X3_3X3 : str
    Absolute file path for LAPLACIANBLUR_3X3_3X3 file
LAPLACIANBLUR_3X3_5X5 : str
    Absolute file path for LAPLACIANBLUR_3X3_5X5 file
LAPLACIANBLUR_3X3_7X7 : str
    Absolute file path for LAPLACIANBLUR_3X3_7X7 file
LAPLACIANBLUR_3X3_9X9 : str
    Absolute file path for LAPLACIANBLUR_3X3_9X9 file
LAPLACIANBLUR_5X5_11X11 : str
    Absolute file path for LAPLACIANBLUR_5X5_11X11 file
LAPLACIANBLUR_5X5_13X13 : str
    Absolute file path for LAPLACIANBLUR_5X5_13X13 file
LAPLACIANBLUR_5X5_15X15 : str
    Absolute file path for LAPLACIANBLUR_5X5_15X15 file
LAPLACIANBLUR_5X5_3X3 : str
    Absolute file path for LAPLACIANBLUR_5X5_3X3 file
LAPLACIANBLUR_5X5_5X5 : str
    Absolute file path for LAPLACIANBLUR_5X5_5X5 file
LAPLACIANBLUR_5X5_7X7 : str
    Absolute file path for LAPLACIANBLUR_5X5_7X7 file
LAPLACIANBLUR_5X5_9X9 : str
    Absolute file path for LAPLACIANBLUR_5X5_9X9 file
LAPLACIANBLUR_7X7_11X11 : str
    Absolute file path for LAPLACIANBLUR_7X7_11X11 file
LAPLACIANBLUR_7X7_13X13 : str
    Absolute file path for LAPLACIANBLUR_7X7_13X13 file
LAPLACIANBLUR_7X7_15X15 : str
    Absolute file path for LAPLACIANBLUR_7X7_15X15 file
LAPLACIANBLUR_7X7_3X3 : str
    Absolute file path for LAPLACIANBLUR_7X7_3X3 file
LAPLACIANBLUR_7X7_5X5 : str
    Absolute file path for LAPLACIANBLUR_7X7_5X5 file
LAPLACIANBLUR_7X7_7X7 : str
    Absolute file path for LAPLACIANBLUR_7X7_7X7 file
LAPLACIANBLUR_7X7_9X9 : str
    Absolute file path for LAPLACIANBLUR_7X7_9X9 file
LAPLACIANBLUR_9X9_11X11 : str
    Absolute file path for LAPLACIANBLUR_9X9_11X11 file
LAPLACIANBLUR_9X9_13X13 : str
    Absolute file path for LAPLACIANBLUR_9X9_13X13 file
LAPLACIANBLUR_9X9_15X15 : str
    Absolute file path for LAPLACIANBLUR_9X9_15X15 file
LAPLACIANBLUR_9X9_3X3 : str
    Absolute file path for LAPLACIANBLUR_9X9_3X3 file
LAPLACIANBLUR_9X9_5X5 : str
    Absolute file path for LAPLACIANBLUR_9X9_5X5 file
LAPLACIANBLUR_9X9_7X7 : str
    Absolute file path for LAPLACIANBLUR_9X9_7X7 file
LAPLACIANBLUR_9X9_9X9 : str
    Absolute file path for LAPLACIANBLUR_9X9_9X9 file
LAPLACIANGRAY_11X11 : str
    Absolute file path for LAPLACIANGRAY_11X11 file
LAPLACIANGRAY_13X13 : str
    Absolute file path for LAPLACIANGRAY_13X13 file
LAPLACIANGRAY_15X15 : str
    Absolute file path for LAPLACIANGRAY_15X15 file
LAPLACIANGRAY_3X3 : str
    Absolute file path for LAPLACIANGRAY_3X3 file
LAPLACIANGRAY_5X5 : str
    Absolute file path for LAPLACIANGRAY_5X5 file
LAPLACIANGRAY_7X7 : str
    Absolute file path for LAPLACIANGRAY_7X7 file
LAPLACIANGRAY_9X9 : str
    Absolute file path for LAPLACIANGRAY_9X9 file
LAPLACIAN_11X11 : str
    Absolute file path for LAPLACIAN_11X11 file
LAPLACIAN_13X13 : str
    Absolute file path for LAPLACIAN_13X13 file
LAPLACIAN_15X15 : str
    Absolute file path for LAPLACIAN_15X15 file
LAPLACIAN_3X3 : str
    Absolute file path for LAPLACIAN_3X3 file
LAPLACIAN_5X5 : str
    Absolute file path for LAPLACIAN_5X5 file
LAPLACIAN_7X7 : str
    Absolute file path for LAPLACIAN_7X7 file
LAPLACIAN_9X9 : str
    Absolute file path for LAPLACIAN_9X9 file
POINTCLOUD : str
    Absolute file path for POINTCLOUD file
SOBEL : str
    Absolute file path for SOBEL file
SOBELBLURGRAY_11X11 : str
    Absolute file path for SOBELBLURGRAY_11X11 file
SOBELBLURGRAY_13X13 : str
    Absolute file path for SOBELBLURGRAY_13X13 file
SOBELBLURGRAY_15X15 : str
    Absolute file path for SOBELBLURGRAY_15X15 file
SOBELBLURGRAY_3X3 : str
    Absolute file path for SOBELBLURGRAY_3X3 file
SOBELBLURGRAY_5X5 : str
    Absolute file path for SOBELBLURGRAY_5X5 file
SOBELBLURGRAY_7X7 : str
    Absolute file path for SOBELBLURGRAY_7X7 file
SOBELBLURGRAY_9X9 : str
    Absolute file path for SOBELBLURGRAY_9X9 file
SOBELBLUR_11X11 : str
    Absolute file path for SOBELBLUR_11X11 file
SOBELBLUR_13X13 : str
    Absolute file path for SOBELBLUR_13X13 file
SOBELBLUR_15X15 : str
    Absolute file path for SOBELBLUR_15X15 file
SOBELBLUR_3X3 : str
    Absolute file path for SOBELBLUR_3X3 file
SOBELBLUR_5X5 : str
    Absolute file path for SOBELBLUR_5X5 file
SOBELBLUR_7X7 : str
    Absolute file path for SOBELBLUR_7X7 file
SOBELBLUR_9X9 : str
    Absolute file path for SOBELBLUR_9X9 file
SOBELGRAY : str
    Absolute file path for SOBELGRAY file
"""

__all__ = [
    "GAUSSIANGRAY_11X11",
    "GAUSSIANGRAY_13X13",
    "GAUSSIANGRAY_15X15",
    "GAUSSIANGRAY_3X3",
    "GAUSSIANGRAY_5X5",
    "GAUSSIANGRAY_7X7",
    "GAUSSIANGRAY_9X9",
    "GAUSSIAN_11X11",
    "GAUSSIAN_13X13",
    "GAUSSIAN_15X15",
    "GAUSSIAN_3X3",
    "GAUSSIAN_5X5",
    "GAUSSIAN_7X7",
    "GAUSSIAN_9X9",
    "LAPLACIANBLURGRAY_11X11_11X11",
    "LAPLACIANBLURGRAY_11X11_13X13",
    "LAPLACIANBLURGRAY_11X11_15X15",
    "LAPLACIANBLURGRAY_11X11_3X3",
    "LAPLACIANBLURGRAY_11X11_5X5",
    "LAPLACIANBLURGRAY_11X11_7X7",
    "LAPLACIANBLURGRAY_11X11_9X9",
    "LAPLACIANBLURGRAY_13X13_11X11",
    "LAPLACIANBLURGRAY_13X13_13X13",
    "LAPLACIANBLURGRAY_13X13_15X15",
    "LAPLACIANBLURGRAY_13X13_3X3",
    "LAPLACIANBLURGRAY_13X13_5X5",
    "LAPLACIANBLURGRAY_13X13_7X7",
    "LAPLACIANBLURGRAY_13X13_9X9",
    "LAPLACIANBLURGRAY_15X15_11X11",
    "LAPLACIANBLURGRAY_15X15_13X13",
    "LAPLACIANBLURGRAY_15X15_15X15",
    "LAPLACIANBLURGRAY_15X15_3X3",
    "LAPLACIANBLURGRAY_15X15_5X5",
    "LAPLACIANBLURGRAY_15X15_7X7",
    "LAPLACIANBLURGRAY_15X15_9X9",
    "LAPLACIANBLURGRAY_3X3_11X11",
    "LAPLACIANBLURGRAY_3X3_13X13",
    "LAPLACIANBLURGRAY_3X3_15X15",
    "LAPLACIANBLURGRAY_3X3_3X3",
    "LAPLACIANBLURGRAY_3X3_5X5",
    "LAPLACIANBLURGRAY_3X3_7X7",
    "LAPLACIANBLURGRAY_3X3_9X9",
    "LAPLACIANBLURGRAY_5X5_11X11",
    "LAPLACIANBLURGRAY_5X5_13X13",
    "LAPLACIANBLURGRAY_5X5_15X15",
    "LAPLACIANBLURGRAY_5X5_3X3",
    "LAPLACIANBLURGRAY_5X5_5X5",
    "LAPLACIANBLURGRAY_5X5_7X7",
    "LAPLACIANBLURGRAY_5X5_9X9",
    "LAPLACIANBLURGRAY_7X7_11X11",
    "LAPLACIANBLURGRAY_7X7_13X13",
    "LAPLACIANBLURGRAY_7X7_15X15",
    "LAPLACIANBLURGRAY_7X7_3X3",
    "LAPLACIANBLURGRAY_7X7_5X5",
    "LAPLACIANBLURGRAY_7X7_7X7",
    "LAPLACIANBLURGRAY_7X7_9X9",
    "LAPLACIANBLURGRAY_9X9_11X11",
    "LAPLACIANBLURGRAY_9X9_13X13",
    "LAPLACIANBLURGRAY_9X9_15X15",
    "LAPLACIANBLURGRAY_9X9_3X3",
    "LAPLACIANBLURGRAY_9X9_5X5",
    "LAPLACIANBLURGRAY_9X9_7X7",
    "LAPLACIANBLURGRAY_9X9_9X9",
    "LAPLACIANBLUR_11X11_11X11",
    "LAPLACIANBLUR_11X11_13X13",
    "LAPLACIANBLUR_11X11_15X15",
    "LAPLACIANBLUR_11X11_3X3",
    "LAPLACIANBLUR_11X11_5X5",
    "LAPLACIANBLUR_11X11_7X7",
    "LAPLACIANBLUR_11X11_9X9",
    "LAPLACIANBLUR_13X13_11X11",
    "LAPLACIANBLUR_13X13_13X13",
    "LAPLACIANBLUR_13X13_15X15",
    "LAPLACIANBLUR_13X13_3X3",
    "LAPLACIANBLUR_13X13_5X5",
    "LAPLACIANBLUR_13X13_7X7",
    "LAPLACIANBLUR_13X13_9X9",
    "LAPLACIANBLUR_15X15_11X11",
    "LAPLACIANBLUR_15X15_13X13",
    "LAPLACIANBLUR_15X15_15X15",
    "LAPLACIANBLUR_15X15_3X3",
    "LAPLACIANBLUR_15X15_5X5",
    "LAPLACIANBLUR_15X15_7X7",
    "LAPLACIANBLUR_15X15_9X9",
    "LAPLACIANBLUR_3X3_11X11",
    "LAPLACIANBLUR_3X3_13X13",
    "LAPLACIANBLUR_3X3_15X15",
    "LAPLACIANBLUR_3X3_3X3",
    "LAPLACIANBLUR_3X3_5X5",
    "LAPLACIANBLUR_3X3_7X7",
    "LAPLACIANBLUR_3X3_9X9",
    "LAPLACIANBLUR_5X5_11X11",
    "LAPLACIANBLUR_5X5_13X13",
    "LAPLACIANBLUR_5X5_15X15",
    "LAPLACIANBLUR_5X5_3X3",
    "LAPLACIANBLUR_5X5_5X5",
    "LAPLACIANBLUR_5X5_7X7",
    "LAPLACIANBLUR_5X5_9X9",
    "LAPLACIANBLUR_7X7_11X11",
    "LAPLACIANBLUR_7X7_13X13",
    "LAPLACIANBLUR_7X7_15X15",
    "LAPLACIANBLUR_7X7_3X3",
    "LAPLACIANBLUR_7X7_5X5",
    "LAPLACIANBLUR_7X7_7X7",
    "LAPLACIANBLUR_7X7_9X9",
    "LAPLACIANBLUR_9X9_11X11",
    "LAPLACIANBLUR_9X9_13X13",
    "LAPLACIANBLUR_9X9_15X15",
    "LAPLACIANBLUR_9X9_3X3",
    "LAPLACIANBLUR_9X9_5X5",
    "LAPLACIANBLUR_9X9_7X7",
    "LAPLACIANBLUR_9X9_9X9",
    "LAPLACIANGRAY_11X11",
    "LAPLACIANGRAY_13X13",
    "LAPLACIANGRAY_15X15",
    "LAPLACIANGRAY_3X3",
    "LAPLACIANGRAY_5X5",
    "LAPLACIANGRAY_7X7",
    "LAPLACIANGRAY_9X9",
    "LAPLACIAN_11X11",
    "LAPLACIAN_13X13",
    "LAPLACIAN_15X15",
    "LAPLACIAN_3X3",
    "LAPLACIAN_5X5",
    "LAPLACIAN_7X7",
    "LAPLACIAN_9X9",
    "POINTCLOUD",
    "SOBEL",
    "SOBELBLURGRAY_11X11",
    "SOBELBLURGRAY_13X13",
    "SOBELBLURGRAY_15X15",
    "SOBELBLURGRAY_3X3",
    "SOBELBLURGRAY_5X5",
    "SOBELBLURGRAY_7X7",
    "SOBELBLURGRAY_9X9",
    "SOBELBLUR_11X11",
    "SOBELBLUR_13X13",
    "SOBELBLUR_15X15",
    "SOBELBLUR_3X3",
    "SOBELBLUR_5X5",
    "SOBELBLUR_7X7",
    "SOBELBLUR_9X9",
    "SOBELGRAY",
]
