# This file is auto-generated by scripts/compile_models.py

"""
Module for compiled models.

Note:
----
This module is auto-generated

Attributes:
----------
shave1 : module
    Contains all the models compiled for [1, 2, 3, 4, 5, 6] shaves
shave2 : module
    Contains all the models compiled for [1, 2, 3, 4, 5, 6] shaves
shave3 : module
    Contains all the models compiled for [1, 2, 3, 4, 5, 6] shaves
shave4 : module
    Contains all the models compiled for [1, 2, 3, 4, 5, 6] shaves
shave5 : module
    Contains all the models compiled for [1, 2, 3, 4, 5, 6] shaves
shave6 : module
    Contains all the models compiled for [1, 2, 3, 4, 5, 6] shaves

"""

from . import shave1, shave2, shave3, shave4, shave5, shave6

__all__ = [
    "shave1",
    "shave2",
    "shave3",
    "shave4",
    "shave5",
    "shave6",
]
