# Copyright (c) 2024 Justin Davis (davisjustin302@gmail.com)
#
# MIT License
# =============================================================================
# This file is auto-generated by scripts/compile_models.py
# =============================================================================

"""
Module for getting all versions (# compiled shaves) of each operation.

Note
-----
This module is auto-generated

Attributes
----------
GFTTBLURGRAY_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblurgray_11x11_shaves6 operation.
GFTTBLURGRAY_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblurgray_13x13_shaves6 operation.
GFTTBLURGRAY_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblurgray_15x15_shaves6 operation.
GFTTBLURGRAY_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblurgray_3x3_shaves6 operation.
GFTTBLURGRAY_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblurgray_5x5_shaves6 operation.
GFTTBLURGRAY_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblurgray_7x7_shaves6 operation.
GFTTBLURGRAY_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblurgray_9x9_shaves6 operation.
GFTTBLUR_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblur_11x11_shaves6 operation.
GFTTBLUR_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblur_13x13_shaves6 operation.
GFTTBLUR_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblur_15x15_shaves6 operation.
GFTTBLUR_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblur_3x3_shaves6 operation.
GFTTBLUR_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblur_5x5_shaves6 operation.
GFTTBLUR_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblur_7x7_shaves6 operation.
GFTTBLUR_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttblur_9x9_shaves6 operation.
GFTTGRAY_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gfttgray_shaves6 operation.
GFTT_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gftt_shaves6 operation.
GAUSSIANGRAY_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussiangray_11x11_shaves6 operation.
GAUSSIANGRAY_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussiangray_13x13_shaves6 operation.
GAUSSIANGRAY_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussiangray_15x15_shaves6 operation.
GAUSSIANGRAY_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussiangray_3x3_shaves6 operation.
GAUSSIANGRAY_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussiangray_5x5_shaves6 operation.
GAUSSIANGRAY_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussiangray_7x7_shaves6 operation.
GAUSSIANGRAY_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussiangray_9x9_shaves6 operation.
GAUSSIAN_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussian_11x11_shaves6 operation.
GAUSSIAN_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussian_13x13_shaves6 operation.
GAUSSIAN_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussian_15x15_shaves6 operation.
GAUSSIAN_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussian_3x3_shaves6 operation.
GAUSSIAN_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussian_5x5_shaves6 operation.
GAUSSIAN_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussian_7x7_shaves6 operation.
GAUSSIAN_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for gaussian_9x9_shaves6 operation.
HARRISBLURGRAY_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblurgray_11x11_shaves6 operation.
HARRISBLURGRAY_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblurgray_13x13_shaves6 operation.
HARRISBLURGRAY_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblurgray_15x15_shaves6 operation.
HARRISBLURGRAY_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblurgray_3x3_shaves6 operation.
HARRISBLURGRAY_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblurgray_5x5_shaves6 operation.
HARRISBLURGRAY_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblurgray_7x7_shaves6 operation.
HARRISBLURGRAY_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblurgray_9x9_shaves6 operation.
HARRISBLUR_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblur_11x11_shaves6 operation.
HARRISBLUR_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblur_13x13_shaves6 operation.
HARRISBLUR_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblur_15x15_shaves6 operation.
HARRISBLUR_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblur_3x3_shaves6 operation.
HARRISBLUR_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblur_5x5_shaves6 operation.
HARRISBLUR_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblur_7x7_shaves6 operation.
HARRISBLUR_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisblur_9x9_shaves6 operation.
HARRISGRAY_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harrisgray_shaves6 operation.
HARRIS_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for harris_shaves6 operation.
HESSIANBLURGRAY_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblurgray_11x11_shaves6 operation.
HESSIANBLURGRAY_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblurgray_13x13_shaves6 operation.
HESSIANBLURGRAY_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblurgray_15x15_shaves6 operation.
HESSIANBLURGRAY_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblurgray_3x3_shaves6 operation.
HESSIANBLURGRAY_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblurgray_5x5_shaves6 operation.
HESSIANBLURGRAY_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblurgray_7x7_shaves6 operation.
HESSIANBLURGRAY_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblurgray_9x9_shaves6 operation.
HESSIANBLUR_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblur_11x11_shaves6 operation.
HESSIANBLUR_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblur_13x13_shaves6 operation.
HESSIANBLUR_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblur_15x15_shaves6 operation.
HESSIANBLUR_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblur_3x3_shaves6 operation.
HESSIANBLUR_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblur_5x5_shaves6 operation.
HESSIANBLUR_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblur_7x7_shaves6 operation.
HESSIANBLUR_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessianblur_9x9_shaves6 operation.
HESSIANGRAY_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessiangray_shaves6 operation.
HESSIAN_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for hessian_shaves6 operation.
LAPLACIANBLURGRAY_11X11_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_11x11_11x11_shaves6 operation.
LAPLACIANBLURGRAY_11X11_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_11x11_13x13_shaves6 operation.
LAPLACIANBLURGRAY_11X11_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_11x11_15x15_shaves6 operation.
LAPLACIANBLURGRAY_11X11_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_11x11_3x3_shaves6 operation.
LAPLACIANBLURGRAY_11X11_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_11x11_5x5_shaves6 operation.
LAPLACIANBLURGRAY_11X11_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_11x11_7x7_shaves6 operation.
LAPLACIANBLURGRAY_11X11_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_11x11_9x9_shaves6 operation.
LAPLACIANBLURGRAY_13X13_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_13x13_11x11_shaves6 operation.
LAPLACIANBLURGRAY_13X13_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_13x13_13x13_shaves6 operation.
LAPLACIANBLURGRAY_13X13_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_13x13_15x15_shaves6 operation.
LAPLACIANBLURGRAY_13X13_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_13x13_3x3_shaves6 operation.
LAPLACIANBLURGRAY_13X13_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_13x13_5x5_shaves6 operation.
LAPLACIANBLURGRAY_13X13_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_13x13_7x7_shaves6 operation.
LAPLACIANBLURGRAY_13X13_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_13x13_9x9_shaves6 operation.
LAPLACIANBLURGRAY_15X15_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_15x15_11x11_shaves6 operation.
LAPLACIANBLURGRAY_15X15_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_15x15_13x13_shaves6 operation.
LAPLACIANBLURGRAY_15X15_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_15x15_15x15_shaves6 operation.
LAPLACIANBLURGRAY_15X15_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_15x15_3x3_shaves6 operation.
LAPLACIANBLURGRAY_15X15_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_15x15_5x5_shaves6 operation.
LAPLACIANBLURGRAY_15X15_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_15x15_7x7_shaves6 operation.
LAPLACIANBLURGRAY_15X15_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_15x15_9x9_shaves6 operation.
LAPLACIANBLURGRAY_3X3_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_3x3_11x11_shaves6 operation.
LAPLACIANBLURGRAY_3X3_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_3x3_13x13_shaves6 operation.
LAPLACIANBLURGRAY_3X3_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_3x3_15x15_shaves6 operation.
LAPLACIANBLURGRAY_3X3_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_3x3_3x3_shaves6 operation.
LAPLACIANBLURGRAY_3X3_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_3x3_5x5_shaves6 operation.
LAPLACIANBLURGRAY_3X3_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_3x3_7x7_shaves6 operation.
LAPLACIANBLURGRAY_3X3_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_3x3_9x9_shaves6 operation.
LAPLACIANBLURGRAY_5X5_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_5x5_11x11_shaves6 operation.
LAPLACIANBLURGRAY_5X5_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_5x5_13x13_shaves6 operation.
LAPLACIANBLURGRAY_5X5_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_5x5_15x15_shaves6 operation.
LAPLACIANBLURGRAY_5X5_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_5x5_3x3_shaves6 operation.
LAPLACIANBLURGRAY_5X5_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_5x5_5x5_shaves6 operation.
LAPLACIANBLURGRAY_5X5_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_5x5_7x7_shaves6 operation.
LAPLACIANBLURGRAY_5X5_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_5x5_9x9_shaves6 operation.
LAPLACIANBLURGRAY_7X7_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_7x7_11x11_shaves6 operation.
LAPLACIANBLURGRAY_7X7_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_7x7_13x13_shaves6 operation.
LAPLACIANBLURGRAY_7X7_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_7x7_15x15_shaves6 operation.
LAPLACIANBLURGRAY_7X7_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_7x7_3x3_shaves6 operation.
LAPLACIANBLURGRAY_7X7_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_7x7_5x5_shaves6 operation.
LAPLACIANBLURGRAY_7X7_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_7x7_7x7_shaves6 operation.
LAPLACIANBLURGRAY_7X7_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_7x7_9x9_shaves6 operation.
LAPLACIANBLURGRAY_9X9_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_9x9_11x11_shaves6 operation.
LAPLACIANBLURGRAY_9X9_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_9x9_13x13_shaves6 operation.
LAPLACIANBLURGRAY_9X9_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_9x9_15x15_shaves6 operation.
LAPLACIANBLURGRAY_9X9_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_9x9_3x3_shaves6 operation.
LAPLACIANBLURGRAY_9X9_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_9x9_5x5_shaves6 operation.
LAPLACIANBLURGRAY_9X9_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_9x9_7x7_shaves6 operation.
LAPLACIANBLURGRAY_9X9_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblurgray_9x9_9x9_shaves6 operation.
LAPLACIANBLUR_11X11_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_11x11_11x11_shaves6 operation.
LAPLACIANBLUR_11X11_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_11x11_13x13_shaves6 operation.
LAPLACIANBLUR_11X11_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_11x11_15x15_shaves6 operation.
LAPLACIANBLUR_11X11_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_11x11_3x3_shaves6 operation.
LAPLACIANBLUR_11X11_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_11x11_5x5_shaves6 operation.
LAPLACIANBLUR_11X11_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_11x11_7x7_shaves6 operation.
LAPLACIANBLUR_11X11_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_11x11_9x9_shaves6 operation.
LAPLACIANBLUR_13X13_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_13x13_11x11_shaves6 operation.
LAPLACIANBLUR_13X13_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_13x13_13x13_shaves6 operation.
LAPLACIANBLUR_13X13_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_13x13_15x15_shaves6 operation.
LAPLACIANBLUR_13X13_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_13x13_3x3_shaves6 operation.
LAPLACIANBLUR_13X13_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_13x13_5x5_shaves6 operation.
LAPLACIANBLUR_13X13_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_13x13_7x7_shaves6 operation.
LAPLACIANBLUR_13X13_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_13x13_9x9_shaves6 operation.
LAPLACIANBLUR_15X15_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_15x15_11x11_shaves6 operation.
LAPLACIANBLUR_15X15_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_15x15_13x13_shaves6 operation.
LAPLACIANBLUR_15X15_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_15x15_15x15_shaves6 operation.
LAPLACIANBLUR_15X15_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_15x15_3x3_shaves6 operation.
LAPLACIANBLUR_15X15_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_15x15_5x5_shaves6 operation.
LAPLACIANBLUR_15X15_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_15x15_7x7_shaves6 operation.
LAPLACIANBLUR_15X15_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_15x15_9x9_shaves6 operation.
LAPLACIANBLUR_3X3_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_3x3_11x11_shaves6 operation.
LAPLACIANBLUR_3X3_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_3x3_13x13_shaves6 operation.
LAPLACIANBLUR_3X3_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_3x3_15x15_shaves6 operation.
LAPLACIANBLUR_3X3_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_3x3_3x3_shaves6 operation.
LAPLACIANBLUR_3X3_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_3x3_5x5_shaves6 operation.
LAPLACIANBLUR_3X3_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_3x3_7x7_shaves6 operation.
LAPLACIANBLUR_3X3_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_3x3_9x9_shaves6 operation.
LAPLACIANBLUR_5X5_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_5x5_11x11_shaves6 operation.
LAPLACIANBLUR_5X5_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_5x5_13x13_shaves6 operation.
LAPLACIANBLUR_5X5_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_5x5_15x15_shaves6 operation.
LAPLACIANBLUR_5X5_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_5x5_3x3_shaves6 operation.
LAPLACIANBLUR_5X5_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_5x5_5x5_shaves6 operation.
LAPLACIANBLUR_5X5_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_5x5_7x7_shaves6 operation.
LAPLACIANBLUR_5X5_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_5x5_9x9_shaves6 operation.
LAPLACIANBLUR_7X7_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_7x7_11x11_shaves6 operation.
LAPLACIANBLUR_7X7_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_7x7_13x13_shaves6 operation.
LAPLACIANBLUR_7X7_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_7x7_15x15_shaves6 operation.
LAPLACIANBLUR_7X7_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_7x7_3x3_shaves6 operation.
LAPLACIANBLUR_7X7_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_7x7_5x5_shaves6 operation.
LAPLACIANBLUR_7X7_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_7x7_7x7_shaves6 operation.
LAPLACIANBLUR_7X7_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_7x7_9x9_shaves6 operation.
LAPLACIANBLUR_9X9_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_9x9_11x11_shaves6 operation.
LAPLACIANBLUR_9X9_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_9x9_13x13_shaves6 operation.
LAPLACIANBLUR_9X9_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_9x9_15x15_shaves6 operation.
LAPLACIANBLUR_9X9_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_9x9_3x3_shaves6 operation.
LAPLACIANBLUR_9X9_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_9x9_5x5_shaves6 operation.
LAPLACIANBLUR_9X9_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_9x9_7x7_shaves6 operation.
LAPLACIANBLUR_9X9_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacianblur_9x9_9x9_shaves6 operation.
LAPLACIANGRAY_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplaciangray_11x11_shaves6 operation.
LAPLACIANGRAY_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplaciangray_13x13_shaves6 operation.
LAPLACIANGRAY_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplaciangray_15x15_shaves6 operation.
LAPLACIANGRAY_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplaciangray_3x3_shaves6 operation.
LAPLACIANGRAY_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplaciangray_5x5_shaves6 operation.
LAPLACIANGRAY_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplaciangray_7x7_shaves6 operation.
LAPLACIANGRAY_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplaciangray_9x9_shaves6 operation.
LAPLACIAN_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacian_11x11_shaves6 operation.
LAPLACIAN_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacian_13x13_shaves6 operation.
LAPLACIAN_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacian_15x15_shaves6 operation.
LAPLACIAN_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacian_3x3_shaves6 operation.
LAPLACIAN_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacian_5x5_shaves6 operation.
LAPLACIAN_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacian_7x7_shaves6 operation.
LAPLACIAN_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laplacian_9x9_shaves6 operation.
LASERSCAN_10_1_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laserscan_10_1_shaves6 operation.
LASERSCAN_10_3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laserscan_10_3_shaves6 operation.
LASERSCAN_10_5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laserscan_10_5_shaves6 operation.
LASERSCAN_20_1_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laserscan_20_1_shaves6 operation.
LASERSCAN_20_3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laserscan_20_3_shaves6 operation.
LASERSCAN_20_5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laserscan_20_5_shaves6 operation.
LASERSCAN_5_1_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laserscan_5_1_shaves6 operation.
LASERSCAN_5_3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laserscan_5_3_shaves6 operation.
LASERSCAN_5_5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for laserscan_5_5_shaves6 operation.
POINTCLOUD_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for pointcloud_shaves6 operation.
SOBELBLURGRAY_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblurgray_11x11_shaves6 operation.
SOBELBLURGRAY_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblurgray_13x13_shaves6 operation.
SOBELBLURGRAY_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblurgray_15x15_shaves6 operation.
SOBELBLURGRAY_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblurgray_3x3_shaves6 operation.
SOBELBLURGRAY_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblurgray_5x5_shaves6 operation.
SOBELBLURGRAY_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblurgray_7x7_shaves6 operation.
SOBELBLURGRAY_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblurgray_9x9_shaves6 operation.
SOBELBLUR_11X11_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblur_11x11_shaves6 operation.
SOBELBLUR_13X13_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblur_13x13_shaves6 operation.
SOBELBLUR_15X15_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblur_15x15_shaves6 operation.
SOBELBLUR_3X3_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblur_3x3_shaves6 operation.
SOBELBLUR_5X5_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblur_5x5_shaves6 operation.
SOBELBLUR_7X7_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblur_7x7_shaves6 operation.
SOBELBLUR_9X9_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelblur_9x9_shaves6 operation.
SOBELGRAY_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobelgray_shaves6 operation.
SOBEL_SHAVES6 : tuple[Path, ...]
    tuple of all wrappers for sobel_shaves6 operation.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

from . import shave1
from . import shave2
from . import shave3
from . import shave4
from . import shave5
from . import shave6


GFTTBLURGRAY_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLURGRAY_11X11_SHAVES6,
    shave2.GFTTBLURGRAY_11X11_SHAVES6,
    shave3.GFTTBLURGRAY_11X11_SHAVES6,
    shave4.GFTTBLURGRAY_11X11_SHAVES6,
    shave5.GFTTBLURGRAY_11X11_SHAVES6,
    shave6.GFTTBLURGRAY_11X11_SHAVES6,
)

GFTTBLURGRAY_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLURGRAY_13X13_SHAVES6,
    shave2.GFTTBLURGRAY_13X13_SHAVES6,
    shave3.GFTTBLURGRAY_13X13_SHAVES6,
    shave4.GFTTBLURGRAY_13X13_SHAVES6,
    shave5.GFTTBLURGRAY_13X13_SHAVES6,
    shave6.GFTTBLURGRAY_13X13_SHAVES6,
)

GFTTBLURGRAY_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLURGRAY_15X15_SHAVES6,
    shave2.GFTTBLURGRAY_15X15_SHAVES6,
    shave3.GFTTBLURGRAY_15X15_SHAVES6,
    shave4.GFTTBLURGRAY_15X15_SHAVES6,
    shave5.GFTTBLURGRAY_15X15_SHAVES6,
    shave6.GFTTBLURGRAY_15X15_SHAVES6,
)

GFTTBLURGRAY_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLURGRAY_3X3_SHAVES6,
    shave2.GFTTBLURGRAY_3X3_SHAVES6,
    shave3.GFTTBLURGRAY_3X3_SHAVES6,
    shave4.GFTTBLURGRAY_3X3_SHAVES6,
    shave5.GFTTBLURGRAY_3X3_SHAVES6,
    shave6.GFTTBLURGRAY_3X3_SHAVES6,
)

GFTTBLURGRAY_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLURGRAY_5X5_SHAVES6,
    shave2.GFTTBLURGRAY_5X5_SHAVES6,
    shave3.GFTTBLURGRAY_5X5_SHAVES6,
    shave4.GFTTBLURGRAY_5X5_SHAVES6,
    shave5.GFTTBLURGRAY_5X5_SHAVES6,
    shave6.GFTTBLURGRAY_5X5_SHAVES6,
)

GFTTBLURGRAY_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLURGRAY_7X7_SHAVES6,
    shave2.GFTTBLURGRAY_7X7_SHAVES6,
    shave3.GFTTBLURGRAY_7X7_SHAVES6,
    shave4.GFTTBLURGRAY_7X7_SHAVES6,
    shave5.GFTTBLURGRAY_7X7_SHAVES6,
    shave6.GFTTBLURGRAY_7X7_SHAVES6,
)

GFTTBLURGRAY_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLURGRAY_9X9_SHAVES6,
    shave2.GFTTBLURGRAY_9X9_SHAVES6,
    shave3.GFTTBLURGRAY_9X9_SHAVES6,
    shave4.GFTTBLURGRAY_9X9_SHAVES6,
    shave5.GFTTBLURGRAY_9X9_SHAVES6,
    shave6.GFTTBLURGRAY_9X9_SHAVES6,
)

GFTTBLUR_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLUR_11X11_SHAVES6,
    shave2.GFTTBLUR_11X11_SHAVES6,
    shave3.GFTTBLUR_11X11_SHAVES6,
    shave4.GFTTBLUR_11X11_SHAVES6,
    shave5.GFTTBLUR_11X11_SHAVES6,
    shave6.GFTTBLUR_11X11_SHAVES6,
)

GFTTBLUR_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLUR_13X13_SHAVES6,
    shave2.GFTTBLUR_13X13_SHAVES6,
    shave3.GFTTBLUR_13X13_SHAVES6,
    shave4.GFTTBLUR_13X13_SHAVES6,
    shave5.GFTTBLUR_13X13_SHAVES6,
    shave6.GFTTBLUR_13X13_SHAVES6,
)

GFTTBLUR_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLUR_15X15_SHAVES6,
    shave2.GFTTBLUR_15X15_SHAVES6,
    shave3.GFTTBLUR_15X15_SHAVES6,
    shave4.GFTTBLUR_15X15_SHAVES6,
    shave5.GFTTBLUR_15X15_SHAVES6,
    shave6.GFTTBLUR_15X15_SHAVES6,
)

GFTTBLUR_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLUR_3X3_SHAVES6,
    shave2.GFTTBLUR_3X3_SHAVES6,
    shave3.GFTTBLUR_3X3_SHAVES6,
    shave4.GFTTBLUR_3X3_SHAVES6,
    shave5.GFTTBLUR_3X3_SHAVES6,
    shave6.GFTTBLUR_3X3_SHAVES6,
)

GFTTBLUR_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLUR_5X5_SHAVES6,
    shave2.GFTTBLUR_5X5_SHAVES6,
    shave3.GFTTBLUR_5X5_SHAVES6,
    shave4.GFTTBLUR_5X5_SHAVES6,
    shave5.GFTTBLUR_5X5_SHAVES6,
    shave6.GFTTBLUR_5X5_SHAVES6,
)

GFTTBLUR_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLUR_7X7_SHAVES6,
    shave2.GFTTBLUR_7X7_SHAVES6,
    shave3.GFTTBLUR_7X7_SHAVES6,
    shave4.GFTTBLUR_7X7_SHAVES6,
    shave5.GFTTBLUR_7X7_SHAVES6,
    shave6.GFTTBLUR_7X7_SHAVES6,
)

GFTTBLUR_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTBLUR_9X9_SHAVES6,
    shave2.GFTTBLUR_9X9_SHAVES6,
    shave3.GFTTBLUR_9X9_SHAVES6,
    shave4.GFTTBLUR_9X9_SHAVES6,
    shave5.GFTTBLUR_9X9_SHAVES6,
    shave6.GFTTBLUR_9X9_SHAVES6,
)

GFTTGRAY_SHAVES6: tuple[Path, ...] = (
    shave1.GFTTGRAY_SHAVES6,
    shave2.GFTTGRAY_SHAVES6,
    shave3.GFTTGRAY_SHAVES6,
    shave4.GFTTGRAY_SHAVES6,
    shave5.GFTTGRAY_SHAVES6,
    shave6.GFTTGRAY_SHAVES6,
)

GFTT_SHAVES6: tuple[Path, ...] = (
    shave1.GFTT_SHAVES6,
    shave2.GFTT_SHAVES6,
    shave3.GFTT_SHAVES6,
    shave4.GFTT_SHAVES6,
    shave5.GFTT_SHAVES6,
    shave6.GFTT_SHAVES6,
)

GAUSSIANGRAY_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIANGRAY_11X11_SHAVES6,
    shave2.GAUSSIANGRAY_11X11_SHAVES6,
    shave3.GAUSSIANGRAY_11X11_SHAVES6,
    shave4.GAUSSIANGRAY_11X11_SHAVES6,
    shave5.GAUSSIANGRAY_11X11_SHAVES6,
    shave6.GAUSSIANGRAY_11X11_SHAVES6,
)

GAUSSIANGRAY_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIANGRAY_13X13_SHAVES6,
    shave2.GAUSSIANGRAY_13X13_SHAVES6,
    shave3.GAUSSIANGRAY_13X13_SHAVES6,
    shave4.GAUSSIANGRAY_13X13_SHAVES6,
    shave5.GAUSSIANGRAY_13X13_SHAVES6,
    shave6.GAUSSIANGRAY_13X13_SHAVES6,
)

GAUSSIANGRAY_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIANGRAY_15X15_SHAVES6,
    shave2.GAUSSIANGRAY_15X15_SHAVES6,
    shave3.GAUSSIANGRAY_15X15_SHAVES6,
    shave4.GAUSSIANGRAY_15X15_SHAVES6,
    shave5.GAUSSIANGRAY_15X15_SHAVES6,
    shave6.GAUSSIANGRAY_15X15_SHAVES6,
)

GAUSSIANGRAY_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIANGRAY_3X3_SHAVES6,
    shave2.GAUSSIANGRAY_3X3_SHAVES6,
    shave3.GAUSSIANGRAY_3X3_SHAVES6,
    shave4.GAUSSIANGRAY_3X3_SHAVES6,
    shave5.GAUSSIANGRAY_3X3_SHAVES6,
    shave6.GAUSSIANGRAY_3X3_SHAVES6,
)

GAUSSIANGRAY_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIANGRAY_5X5_SHAVES6,
    shave2.GAUSSIANGRAY_5X5_SHAVES6,
    shave3.GAUSSIANGRAY_5X5_SHAVES6,
    shave4.GAUSSIANGRAY_5X5_SHAVES6,
    shave5.GAUSSIANGRAY_5X5_SHAVES6,
    shave6.GAUSSIANGRAY_5X5_SHAVES6,
)

GAUSSIANGRAY_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIANGRAY_7X7_SHAVES6,
    shave2.GAUSSIANGRAY_7X7_SHAVES6,
    shave3.GAUSSIANGRAY_7X7_SHAVES6,
    shave4.GAUSSIANGRAY_7X7_SHAVES6,
    shave5.GAUSSIANGRAY_7X7_SHAVES6,
    shave6.GAUSSIANGRAY_7X7_SHAVES6,
)

GAUSSIANGRAY_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIANGRAY_9X9_SHAVES6,
    shave2.GAUSSIANGRAY_9X9_SHAVES6,
    shave3.GAUSSIANGRAY_9X9_SHAVES6,
    shave4.GAUSSIANGRAY_9X9_SHAVES6,
    shave5.GAUSSIANGRAY_9X9_SHAVES6,
    shave6.GAUSSIANGRAY_9X9_SHAVES6,
)

GAUSSIAN_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIAN_11X11_SHAVES6,
    shave2.GAUSSIAN_11X11_SHAVES6,
    shave3.GAUSSIAN_11X11_SHAVES6,
    shave4.GAUSSIAN_11X11_SHAVES6,
    shave5.GAUSSIAN_11X11_SHAVES6,
    shave6.GAUSSIAN_11X11_SHAVES6,
)

GAUSSIAN_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIAN_13X13_SHAVES6,
    shave2.GAUSSIAN_13X13_SHAVES6,
    shave3.GAUSSIAN_13X13_SHAVES6,
    shave4.GAUSSIAN_13X13_SHAVES6,
    shave5.GAUSSIAN_13X13_SHAVES6,
    shave6.GAUSSIAN_13X13_SHAVES6,
)

GAUSSIAN_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIAN_15X15_SHAVES6,
    shave2.GAUSSIAN_15X15_SHAVES6,
    shave3.GAUSSIAN_15X15_SHAVES6,
    shave4.GAUSSIAN_15X15_SHAVES6,
    shave5.GAUSSIAN_15X15_SHAVES6,
    shave6.GAUSSIAN_15X15_SHAVES6,
)

GAUSSIAN_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIAN_3X3_SHAVES6,
    shave2.GAUSSIAN_3X3_SHAVES6,
    shave3.GAUSSIAN_3X3_SHAVES6,
    shave4.GAUSSIAN_3X3_SHAVES6,
    shave5.GAUSSIAN_3X3_SHAVES6,
    shave6.GAUSSIAN_3X3_SHAVES6,
)

GAUSSIAN_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIAN_5X5_SHAVES6,
    shave2.GAUSSIAN_5X5_SHAVES6,
    shave3.GAUSSIAN_5X5_SHAVES6,
    shave4.GAUSSIAN_5X5_SHAVES6,
    shave5.GAUSSIAN_5X5_SHAVES6,
    shave6.GAUSSIAN_5X5_SHAVES6,
)

GAUSSIAN_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIAN_7X7_SHAVES6,
    shave2.GAUSSIAN_7X7_SHAVES6,
    shave3.GAUSSIAN_7X7_SHAVES6,
    shave4.GAUSSIAN_7X7_SHAVES6,
    shave5.GAUSSIAN_7X7_SHAVES6,
    shave6.GAUSSIAN_7X7_SHAVES6,
)

GAUSSIAN_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.GAUSSIAN_9X9_SHAVES6,
    shave2.GAUSSIAN_9X9_SHAVES6,
    shave3.GAUSSIAN_9X9_SHAVES6,
    shave4.GAUSSIAN_9X9_SHAVES6,
    shave5.GAUSSIAN_9X9_SHAVES6,
    shave6.GAUSSIAN_9X9_SHAVES6,
)

HARRISBLURGRAY_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLURGRAY_11X11_SHAVES6,
    shave2.HARRISBLURGRAY_11X11_SHAVES6,
    shave3.HARRISBLURGRAY_11X11_SHAVES6,
    shave4.HARRISBLURGRAY_11X11_SHAVES6,
    shave5.HARRISBLURGRAY_11X11_SHAVES6,
    shave6.HARRISBLURGRAY_11X11_SHAVES6,
)

HARRISBLURGRAY_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLURGRAY_13X13_SHAVES6,
    shave2.HARRISBLURGRAY_13X13_SHAVES6,
    shave3.HARRISBLURGRAY_13X13_SHAVES6,
    shave4.HARRISBLURGRAY_13X13_SHAVES6,
    shave5.HARRISBLURGRAY_13X13_SHAVES6,
    shave6.HARRISBLURGRAY_13X13_SHAVES6,
)

HARRISBLURGRAY_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLURGRAY_15X15_SHAVES6,
    shave2.HARRISBLURGRAY_15X15_SHAVES6,
    shave3.HARRISBLURGRAY_15X15_SHAVES6,
    shave4.HARRISBLURGRAY_15X15_SHAVES6,
    shave5.HARRISBLURGRAY_15X15_SHAVES6,
    shave6.HARRISBLURGRAY_15X15_SHAVES6,
)

HARRISBLURGRAY_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLURGRAY_3X3_SHAVES6,
    shave2.HARRISBLURGRAY_3X3_SHAVES6,
    shave3.HARRISBLURGRAY_3X3_SHAVES6,
    shave4.HARRISBLURGRAY_3X3_SHAVES6,
    shave5.HARRISBLURGRAY_3X3_SHAVES6,
    shave6.HARRISBLURGRAY_3X3_SHAVES6,
)

HARRISBLURGRAY_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLURGRAY_5X5_SHAVES6,
    shave2.HARRISBLURGRAY_5X5_SHAVES6,
    shave3.HARRISBLURGRAY_5X5_SHAVES6,
    shave4.HARRISBLURGRAY_5X5_SHAVES6,
    shave5.HARRISBLURGRAY_5X5_SHAVES6,
    shave6.HARRISBLURGRAY_5X5_SHAVES6,
)

HARRISBLURGRAY_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLURGRAY_7X7_SHAVES6,
    shave2.HARRISBLURGRAY_7X7_SHAVES6,
    shave3.HARRISBLURGRAY_7X7_SHAVES6,
    shave4.HARRISBLURGRAY_7X7_SHAVES6,
    shave5.HARRISBLURGRAY_7X7_SHAVES6,
    shave6.HARRISBLURGRAY_7X7_SHAVES6,
)

HARRISBLURGRAY_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLURGRAY_9X9_SHAVES6,
    shave2.HARRISBLURGRAY_9X9_SHAVES6,
    shave3.HARRISBLURGRAY_9X9_SHAVES6,
    shave4.HARRISBLURGRAY_9X9_SHAVES6,
    shave5.HARRISBLURGRAY_9X9_SHAVES6,
    shave6.HARRISBLURGRAY_9X9_SHAVES6,
)

HARRISBLUR_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLUR_11X11_SHAVES6,
    shave2.HARRISBLUR_11X11_SHAVES6,
    shave3.HARRISBLUR_11X11_SHAVES6,
    shave4.HARRISBLUR_11X11_SHAVES6,
    shave5.HARRISBLUR_11X11_SHAVES6,
    shave6.HARRISBLUR_11X11_SHAVES6,
)

HARRISBLUR_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLUR_13X13_SHAVES6,
    shave2.HARRISBLUR_13X13_SHAVES6,
    shave3.HARRISBLUR_13X13_SHAVES6,
    shave4.HARRISBLUR_13X13_SHAVES6,
    shave5.HARRISBLUR_13X13_SHAVES6,
    shave6.HARRISBLUR_13X13_SHAVES6,
)

HARRISBLUR_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLUR_15X15_SHAVES6,
    shave2.HARRISBLUR_15X15_SHAVES6,
    shave3.HARRISBLUR_15X15_SHAVES6,
    shave4.HARRISBLUR_15X15_SHAVES6,
    shave5.HARRISBLUR_15X15_SHAVES6,
    shave6.HARRISBLUR_15X15_SHAVES6,
)

HARRISBLUR_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLUR_3X3_SHAVES6,
    shave2.HARRISBLUR_3X3_SHAVES6,
    shave3.HARRISBLUR_3X3_SHAVES6,
    shave4.HARRISBLUR_3X3_SHAVES6,
    shave5.HARRISBLUR_3X3_SHAVES6,
    shave6.HARRISBLUR_3X3_SHAVES6,
)

HARRISBLUR_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLUR_5X5_SHAVES6,
    shave2.HARRISBLUR_5X5_SHAVES6,
    shave3.HARRISBLUR_5X5_SHAVES6,
    shave4.HARRISBLUR_5X5_SHAVES6,
    shave5.HARRISBLUR_5X5_SHAVES6,
    shave6.HARRISBLUR_5X5_SHAVES6,
)

HARRISBLUR_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLUR_7X7_SHAVES6,
    shave2.HARRISBLUR_7X7_SHAVES6,
    shave3.HARRISBLUR_7X7_SHAVES6,
    shave4.HARRISBLUR_7X7_SHAVES6,
    shave5.HARRISBLUR_7X7_SHAVES6,
    shave6.HARRISBLUR_7X7_SHAVES6,
)

HARRISBLUR_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISBLUR_9X9_SHAVES6,
    shave2.HARRISBLUR_9X9_SHAVES6,
    shave3.HARRISBLUR_9X9_SHAVES6,
    shave4.HARRISBLUR_9X9_SHAVES6,
    shave5.HARRISBLUR_9X9_SHAVES6,
    shave6.HARRISBLUR_9X9_SHAVES6,
)

HARRISGRAY_SHAVES6: tuple[Path, ...] = (
    shave1.HARRISGRAY_SHAVES6,
    shave2.HARRISGRAY_SHAVES6,
    shave3.HARRISGRAY_SHAVES6,
    shave4.HARRISGRAY_SHAVES6,
    shave5.HARRISGRAY_SHAVES6,
    shave6.HARRISGRAY_SHAVES6,
)

HARRIS_SHAVES6: tuple[Path, ...] = (
    shave1.HARRIS_SHAVES6,
    shave2.HARRIS_SHAVES6,
    shave3.HARRIS_SHAVES6,
    shave4.HARRIS_SHAVES6,
    shave5.HARRIS_SHAVES6,
    shave6.HARRIS_SHAVES6,
)

HESSIANBLURGRAY_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLURGRAY_11X11_SHAVES6,
    shave2.HESSIANBLURGRAY_11X11_SHAVES6,
    shave3.HESSIANBLURGRAY_11X11_SHAVES6,
    shave4.HESSIANBLURGRAY_11X11_SHAVES6,
    shave5.HESSIANBLURGRAY_11X11_SHAVES6,
    shave6.HESSIANBLURGRAY_11X11_SHAVES6,
)

HESSIANBLURGRAY_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLURGRAY_13X13_SHAVES6,
    shave2.HESSIANBLURGRAY_13X13_SHAVES6,
    shave3.HESSIANBLURGRAY_13X13_SHAVES6,
    shave4.HESSIANBLURGRAY_13X13_SHAVES6,
    shave5.HESSIANBLURGRAY_13X13_SHAVES6,
    shave6.HESSIANBLURGRAY_13X13_SHAVES6,
)

HESSIANBLURGRAY_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLURGRAY_15X15_SHAVES6,
    shave2.HESSIANBLURGRAY_15X15_SHAVES6,
    shave3.HESSIANBLURGRAY_15X15_SHAVES6,
    shave4.HESSIANBLURGRAY_15X15_SHAVES6,
    shave5.HESSIANBLURGRAY_15X15_SHAVES6,
    shave6.HESSIANBLURGRAY_15X15_SHAVES6,
)

HESSIANBLURGRAY_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLURGRAY_3X3_SHAVES6,
    shave2.HESSIANBLURGRAY_3X3_SHAVES6,
    shave3.HESSIANBLURGRAY_3X3_SHAVES6,
    shave4.HESSIANBLURGRAY_3X3_SHAVES6,
    shave5.HESSIANBLURGRAY_3X3_SHAVES6,
    shave6.HESSIANBLURGRAY_3X3_SHAVES6,
)

HESSIANBLURGRAY_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLURGRAY_5X5_SHAVES6,
    shave2.HESSIANBLURGRAY_5X5_SHAVES6,
    shave3.HESSIANBLURGRAY_5X5_SHAVES6,
    shave4.HESSIANBLURGRAY_5X5_SHAVES6,
    shave5.HESSIANBLURGRAY_5X5_SHAVES6,
    shave6.HESSIANBLURGRAY_5X5_SHAVES6,
)

HESSIANBLURGRAY_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLURGRAY_7X7_SHAVES6,
    shave2.HESSIANBLURGRAY_7X7_SHAVES6,
    shave3.HESSIANBLURGRAY_7X7_SHAVES6,
    shave4.HESSIANBLURGRAY_7X7_SHAVES6,
    shave5.HESSIANBLURGRAY_7X7_SHAVES6,
    shave6.HESSIANBLURGRAY_7X7_SHAVES6,
)

HESSIANBLURGRAY_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLURGRAY_9X9_SHAVES6,
    shave2.HESSIANBLURGRAY_9X9_SHAVES6,
    shave3.HESSIANBLURGRAY_9X9_SHAVES6,
    shave4.HESSIANBLURGRAY_9X9_SHAVES6,
    shave5.HESSIANBLURGRAY_9X9_SHAVES6,
    shave6.HESSIANBLURGRAY_9X9_SHAVES6,
)

HESSIANBLUR_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLUR_11X11_SHAVES6,
    shave2.HESSIANBLUR_11X11_SHAVES6,
    shave3.HESSIANBLUR_11X11_SHAVES6,
    shave4.HESSIANBLUR_11X11_SHAVES6,
    shave5.HESSIANBLUR_11X11_SHAVES6,
    shave6.HESSIANBLUR_11X11_SHAVES6,
)

HESSIANBLUR_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLUR_13X13_SHAVES6,
    shave2.HESSIANBLUR_13X13_SHAVES6,
    shave3.HESSIANBLUR_13X13_SHAVES6,
    shave4.HESSIANBLUR_13X13_SHAVES6,
    shave5.HESSIANBLUR_13X13_SHAVES6,
    shave6.HESSIANBLUR_13X13_SHAVES6,
)

HESSIANBLUR_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLUR_15X15_SHAVES6,
    shave2.HESSIANBLUR_15X15_SHAVES6,
    shave3.HESSIANBLUR_15X15_SHAVES6,
    shave4.HESSIANBLUR_15X15_SHAVES6,
    shave5.HESSIANBLUR_15X15_SHAVES6,
    shave6.HESSIANBLUR_15X15_SHAVES6,
)

HESSIANBLUR_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLUR_3X3_SHAVES6,
    shave2.HESSIANBLUR_3X3_SHAVES6,
    shave3.HESSIANBLUR_3X3_SHAVES6,
    shave4.HESSIANBLUR_3X3_SHAVES6,
    shave5.HESSIANBLUR_3X3_SHAVES6,
    shave6.HESSIANBLUR_3X3_SHAVES6,
)

HESSIANBLUR_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLUR_5X5_SHAVES6,
    shave2.HESSIANBLUR_5X5_SHAVES6,
    shave3.HESSIANBLUR_5X5_SHAVES6,
    shave4.HESSIANBLUR_5X5_SHAVES6,
    shave5.HESSIANBLUR_5X5_SHAVES6,
    shave6.HESSIANBLUR_5X5_SHAVES6,
)

HESSIANBLUR_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLUR_7X7_SHAVES6,
    shave2.HESSIANBLUR_7X7_SHAVES6,
    shave3.HESSIANBLUR_7X7_SHAVES6,
    shave4.HESSIANBLUR_7X7_SHAVES6,
    shave5.HESSIANBLUR_7X7_SHAVES6,
    shave6.HESSIANBLUR_7X7_SHAVES6,
)

HESSIANBLUR_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANBLUR_9X9_SHAVES6,
    shave2.HESSIANBLUR_9X9_SHAVES6,
    shave3.HESSIANBLUR_9X9_SHAVES6,
    shave4.HESSIANBLUR_9X9_SHAVES6,
    shave5.HESSIANBLUR_9X9_SHAVES6,
    shave6.HESSIANBLUR_9X9_SHAVES6,
)

HESSIANGRAY_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIANGRAY_SHAVES6,
    shave2.HESSIANGRAY_SHAVES6,
    shave3.HESSIANGRAY_SHAVES6,
    shave4.HESSIANGRAY_SHAVES6,
    shave5.HESSIANGRAY_SHAVES6,
    shave6.HESSIANGRAY_SHAVES6,
)

HESSIAN_SHAVES6: tuple[Path, ...] = (
    shave1.HESSIAN_SHAVES6,
    shave2.HESSIAN_SHAVES6,
    shave3.HESSIAN_SHAVES6,
    shave4.HESSIAN_SHAVES6,
    shave5.HESSIAN_SHAVES6,
    shave6.HESSIAN_SHAVES6,
)

LAPLACIANBLURGRAY_11X11_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_11X11_11X11_SHAVES6,
    shave2.LAPLACIANBLURGRAY_11X11_11X11_SHAVES6,
    shave3.LAPLACIANBLURGRAY_11X11_11X11_SHAVES6,
    shave4.LAPLACIANBLURGRAY_11X11_11X11_SHAVES6,
    shave5.LAPLACIANBLURGRAY_11X11_11X11_SHAVES6,
    shave6.LAPLACIANBLURGRAY_11X11_11X11_SHAVES6,
)

LAPLACIANBLURGRAY_11X11_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_11X11_13X13_SHAVES6,
    shave2.LAPLACIANBLURGRAY_11X11_13X13_SHAVES6,
    shave3.LAPLACIANBLURGRAY_11X11_13X13_SHAVES6,
    shave4.LAPLACIANBLURGRAY_11X11_13X13_SHAVES6,
    shave5.LAPLACIANBLURGRAY_11X11_13X13_SHAVES6,
    shave6.LAPLACIANBLURGRAY_11X11_13X13_SHAVES6,
)

LAPLACIANBLURGRAY_11X11_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_11X11_15X15_SHAVES6,
    shave2.LAPLACIANBLURGRAY_11X11_15X15_SHAVES6,
    shave3.LAPLACIANBLURGRAY_11X11_15X15_SHAVES6,
    shave4.LAPLACIANBLURGRAY_11X11_15X15_SHAVES6,
    shave5.LAPLACIANBLURGRAY_11X11_15X15_SHAVES6,
    shave6.LAPLACIANBLURGRAY_11X11_15X15_SHAVES6,
)

LAPLACIANBLURGRAY_11X11_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_11X11_3X3_SHAVES6,
    shave2.LAPLACIANBLURGRAY_11X11_3X3_SHAVES6,
    shave3.LAPLACIANBLURGRAY_11X11_3X3_SHAVES6,
    shave4.LAPLACIANBLURGRAY_11X11_3X3_SHAVES6,
    shave5.LAPLACIANBLURGRAY_11X11_3X3_SHAVES6,
    shave6.LAPLACIANBLURGRAY_11X11_3X3_SHAVES6,
)

LAPLACIANBLURGRAY_11X11_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_11X11_5X5_SHAVES6,
    shave2.LAPLACIANBLURGRAY_11X11_5X5_SHAVES6,
    shave3.LAPLACIANBLURGRAY_11X11_5X5_SHAVES6,
    shave4.LAPLACIANBLURGRAY_11X11_5X5_SHAVES6,
    shave5.LAPLACIANBLURGRAY_11X11_5X5_SHAVES6,
    shave6.LAPLACIANBLURGRAY_11X11_5X5_SHAVES6,
)

LAPLACIANBLURGRAY_11X11_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_11X11_7X7_SHAVES6,
    shave2.LAPLACIANBLURGRAY_11X11_7X7_SHAVES6,
    shave3.LAPLACIANBLURGRAY_11X11_7X7_SHAVES6,
    shave4.LAPLACIANBLURGRAY_11X11_7X7_SHAVES6,
    shave5.LAPLACIANBLURGRAY_11X11_7X7_SHAVES6,
    shave6.LAPLACIANBLURGRAY_11X11_7X7_SHAVES6,
)

LAPLACIANBLURGRAY_11X11_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_11X11_9X9_SHAVES6,
    shave2.LAPLACIANBLURGRAY_11X11_9X9_SHAVES6,
    shave3.LAPLACIANBLURGRAY_11X11_9X9_SHAVES6,
    shave4.LAPLACIANBLURGRAY_11X11_9X9_SHAVES6,
    shave5.LAPLACIANBLURGRAY_11X11_9X9_SHAVES6,
    shave6.LAPLACIANBLURGRAY_11X11_9X9_SHAVES6,
)

LAPLACIANBLURGRAY_13X13_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_13X13_11X11_SHAVES6,
    shave2.LAPLACIANBLURGRAY_13X13_11X11_SHAVES6,
    shave3.LAPLACIANBLURGRAY_13X13_11X11_SHAVES6,
    shave4.LAPLACIANBLURGRAY_13X13_11X11_SHAVES6,
    shave5.LAPLACIANBLURGRAY_13X13_11X11_SHAVES6,
    shave6.LAPLACIANBLURGRAY_13X13_11X11_SHAVES6,
)

LAPLACIANBLURGRAY_13X13_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_13X13_13X13_SHAVES6,
    shave2.LAPLACIANBLURGRAY_13X13_13X13_SHAVES6,
    shave3.LAPLACIANBLURGRAY_13X13_13X13_SHAVES6,
    shave4.LAPLACIANBLURGRAY_13X13_13X13_SHAVES6,
    shave5.LAPLACIANBLURGRAY_13X13_13X13_SHAVES6,
    shave6.LAPLACIANBLURGRAY_13X13_13X13_SHAVES6,
)

LAPLACIANBLURGRAY_13X13_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_13X13_15X15_SHAVES6,
    shave2.LAPLACIANBLURGRAY_13X13_15X15_SHAVES6,
    shave3.LAPLACIANBLURGRAY_13X13_15X15_SHAVES6,
    shave4.LAPLACIANBLURGRAY_13X13_15X15_SHAVES6,
    shave5.LAPLACIANBLURGRAY_13X13_15X15_SHAVES6,
    shave6.LAPLACIANBLURGRAY_13X13_15X15_SHAVES6,
)

LAPLACIANBLURGRAY_13X13_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_13X13_3X3_SHAVES6,
    shave2.LAPLACIANBLURGRAY_13X13_3X3_SHAVES6,
    shave3.LAPLACIANBLURGRAY_13X13_3X3_SHAVES6,
    shave4.LAPLACIANBLURGRAY_13X13_3X3_SHAVES6,
    shave5.LAPLACIANBLURGRAY_13X13_3X3_SHAVES6,
    shave6.LAPLACIANBLURGRAY_13X13_3X3_SHAVES6,
)

LAPLACIANBLURGRAY_13X13_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_13X13_5X5_SHAVES6,
    shave2.LAPLACIANBLURGRAY_13X13_5X5_SHAVES6,
    shave3.LAPLACIANBLURGRAY_13X13_5X5_SHAVES6,
    shave4.LAPLACIANBLURGRAY_13X13_5X5_SHAVES6,
    shave5.LAPLACIANBLURGRAY_13X13_5X5_SHAVES6,
    shave6.LAPLACIANBLURGRAY_13X13_5X5_SHAVES6,
)

LAPLACIANBLURGRAY_13X13_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_13X13_7X7_SHAVES6,
    shave2.LAPLACIANBLURGRAY_13X13_7X7_SHAVES6,
    shave3.LAPLACIANBLURGRAY_13X13_7X7_SHAVES6,
    shave4.LAPLACIANBLURGRAY_13X13_7X7_SHAVES6,
    shave5.LAPLACIANBLURGRAY_13X13_7X7_SHAVES6,
    shave6.LAPLACIANBLURGRAY_13X13_7X7_SHAVES6,
)

LAPLACIANBLURGRAY_13X13_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_13X13_9X9_SHAVES6,
    shave2.LAPLACIANBLURGRAY_13X13_9X9_SHAVES6,
    shave3.LAPLACIANBLURGRAY_13X13_9X9_SHAVES6,
    shave4.LAPLACIANBLURGRAY_13X13_9X9_SHAVES6,
    shave5.LAPLACIANBLURGRAY_13X13_9X9_SHAVES6,
    shave6.LAPLACIANBLURGRAY_13X13_9X9_SHAVES6,
)

LAPLACIANBLURGRAY_15X15_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_15X15_11X11_SHAVES6,
    shave2.LAPLACIANBLURGRAY_15X15_11X11_SHAVES6,
    shave3.LAPLACIANBLURGRAY_15X15_11X11_SHAVES6,
    shave4.LAPLACIANBLURGRAY_15X15_11X11_SHAVES6,
    shave5.LAPLACIANBLURGRAY_15X15_11X11_SHAVES6,
    shave6.LAPLACIANBLURGRAY_15X15_11X11_SHAVES6,
)

LAPLACIANBLURGRAY_15X15_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_15X15_13X13_SHAVES6,
    shave2.LAPLACIANBLURGRAY_15X15_13X13_SHAVES6,
    shave3.LAPLACIANBLURGRAY_15X15_13X13_SHAVES6,
    shave4.LAPLACIANBLURGRAY_15X15_13X13_SHAVES6,
    shave5.LAPLACIANBLURGRAY_15X15_13X13_SHAVES6,
    shave6.LAPLACIANBLURGRAY_15X15_13X13_SHAVES6,
)

LAPLACIANBLURGRAY_15X15_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_15X15_15X15_SHAVES6,
    shave2.LAPLACIANBLURGRAY_15X15_15X15_SHAVES6,
    shave3.LAPLACIANBLURGRAY_15X15_15X15_SHAVES6,
    shave4.LAPLACIANBLURGRAY_15X15_15X15_SHAVES6,
    shave5.LAPLACIANBLURGRAY_15X15_15X15_SHAVES6,
    shave6.LAPLACIANBLURGRAY_15X15_15X15_SHAVES6,
)

LAPLACIANBLURGRAY_15X15_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_15X15_3X3_SHAVES6,
    shave2.LAPLACIANBLURGRAY_15X15_3X3_SHAVES6,
    shave3.LAPLACIANBLURGRAY_15X15_3X3_SHAVES6,
    shave4.LAPLACIANBLURGRAY_15X15_3X3_SHAVES6,
    shave5.LAPLACIANBLURGRAY_15X15_3X3_SHAVES6,
    shave6.LAPLACIANBLURGRAY_15X15_3X3_SHAVES6,
)

LAPLACIANBLURGRAY_15X15_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_15X15_5X5_SHAVES6,
    shave2.LAPLACIANBLURGRAY_15X15_5X5_SHAVES6,
    shave3.LAPLACIANBLURGRAY_15X15_5X5_SHAVES6,
    shave4.LAPLACIANBLURGRAY_15X15_5X5_SHAVES6,
    shave5.LAPLACIANBLURGRAY_15X15_5X5_SHAVES6,
    shave6.LAPLACIANBLURGRAY_15X15_5X5_SHAVES6,
)

LAPLACIANBLURGRAY_15X15_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_15X15_7X7_SHAVES6,
    shave2.LAPLACIANBLURGRAY_15X15_7X7_SHAVES6,
    shave3.LAPLACIANBLURGRAY_15X15_7X7_SHAVES6,
    shave4.LAPLACIANBLURGRAY_15X15_7X7_SHAVES6,
    shave5.LAPLACIANBLURGRAY_15X15_7X7_SHAVES6,
    shave6.LAPLACIANBLURGRAY_15X15_7X7_SHAVES6,
)

LAPLACIANBLURGRAY_15X15_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_15X15_9X9_SHAVES6,
    shave2.LAPLACIANBLURGRAY_15X15_9X9_SHAVES6,
    shave3.LAPLACIANBLURGRAY_15X15_9X9_SHAVES6,
    shave4.LAPLACIANBLURGRAY_15X15_9X9_SHAVES6,
    shave5.LAPLACIANBLURGRAY_15X15_9X9_SHAVES6,
    shave6.LAPLACIANBLURGRAY_15X15_9X9_SHAVES6,
)

LAPLACIANBLURGRAY_3X3_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_3X3_11X11_SHAVES6,
    shave2.LAPLACIANBLURGRAY_3X3_11X11_SHAVES6,
    shave3.LAPLACIANBLURGRAY_3X3_11X11_SHAVES6,
    shave4.LAPLACIANBLURGRAY_3X3_11X11_SHAVES6,
    shave5.LAPLACIANBLURGRAY_3X3_11X11_SHAVES6,
    shave6.LAPLACIANBLURGRAY_3X3_11X11_SHAVES6,
)

LAPLACIANBLURGRAY_3X3_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_3X3_13X13_SHAVES6,
    shave2.LAPLACIANBLURGRAY_3X3_13X13_SHAVES6,
    shave3.LAPLACIANBLURGRAY_3X3_13X13_SHAVES6,
    shave4.LAPLACIANBLURGRAY_3X3_13X13_SHAVES6,
    shave5.LAPLACIANBLURGRAY_3X3_13X13_SHAVES6,
    shave6.LAPLACIANBLURGRAY_3X3_13X13_SHAVES6,
)

LAPLACIANBLURGRAY_3X3_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_3X3_15X15_SHAVES6,
    shave2.LAPLACIANBLURGRAY_3X3_15X15_SHAVES6,
    shave3.LAPLACIANBLURGRAY_3X3_15X15_SHAVES6,
    shave4.LAPLACIANBLURGRAY_3X3_15X15_SHAVES6,
    shave5.LAPLACIANBLURGRAY_3X3_15X15_SHAVES6,
    shave6.LAPLACIANBLURGRAY_3X3_15X15_SHAVES6,
)

LAPLACIANBLURGRAY_3X3_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_3X3_3X3_SHAVES6,
    shave2.LAPLACIANBLURGRAY_3X3_3X3_SHAVES6,
    shave3.LAPLACIANBLURGRAY_3X3_3X3_SHAVES6,
    shave4.LAPLACIANBLURGRAY_3X3_3X3_SHAVES6,
    shave5.LAPLACIANBLURGRAY_3X3_3X3_SHAVES6,
    shave6.LAPLACIANBLURGRAY_3X3_3X3_SHAVES6,
)

LAPLACIANBLURGRAY_3X3_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_3X3_5X5_SHAVES6,
    shave2.LAPLACIANBLURGRAY_3X3_5X5_SHAVES6,
    shave3.LAPLACIANBLURGRAY_3X3_5X5_SHAVES6,
    shave4.LAPLACIANBLURGRAY_3X3_5X5_SHAVES6,
    shave5.LAPLACIANBLURGRAY_3X3_5X5_SHAVES6,
    shave6.LAPLACIANBLURGRAY_3X3_5X5_SHAVES6,
)

LAPLACIANBLURGRAY_3X3_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_3X3_7X7_SHAVES6,
    shave2.LAPLACIANBLURGRAY_3X3_7X7_SHAVES6,
    shave3.LAPLACIANBLURGRAY_3X3_7X7_SHAVES6,
    shave4.LAPLACIANBLURGRAY_3X3_7X7_SHAVES6,
    shave5.LAPLACIANBLURGRAY_3X3_7X7_SHAVES6,
    shave6.LAPLACIANBLURGRAY_3X3_7X7_SHAVES6,
)

LAPLACIANBLURGRAY_3X3_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_3X3_9X9_SHAVES6,
    shave2.LAPLACIANBLURGRAY_3X3_9X9_SHAVES6,
    shave3.LAPLACIANBLURGRAY_3X3_9X9_SHAVES6,
    shave4.LAPLACIANBLURGRAY_3X3_9X9_SHAVES6,
    shave5.LAPLACIANBLURGRAY_3X3_9X9_SHAVES6,
    shave6.LAPLACIANBLURGRAY_3X3_9X9_SHAVES6,
)

LAPLACIANBLURGRAY_5X5_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_5X5_11X11_SHAVES6,
    shave2.LAPLACIANBLURGRAY_5X5_11X11_SHAVES6,
    shave3.LAPLACIANBLURGRAY_5X5_11X11_SHAVES6,
    shave4.LAPLACIANBLURGRAY_5X5_11X11_SHAVES6,
    shave5.LAPLACIANBLURGRAY_5X5_11X11_SHAVES6,
    shave6.LAPLACIANBLURGRAY_5X5_11X11_SHAVES6,
)

LAPLACIANBLURGRAY_5X5_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_5X5_13X13_SHAVES6,
    shave2.LAPLACIANBLURGRAY_5X5_13X13_SHAVES6,
    shave3.LAPLACIANBLURGRAY_5X5_13X13_SHAVES6,
    shave4.LAPLACIANBLURGRAY_5X5_13X13_SHAVES6,
    shave5.LAPLACIANBLURGRAY_5X5_13X13_SHAVES6,
    shave6.LAPLACIANBLURGRAY_5X5_13X13_SHAVES6,
)

LAPLACIANBLURGRAY_5X5_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_5X5_15X15_SHAVES6,
    shave2.LAPLACIANBLURGRAY_5X5_15X15_SHAVES6,
    shave3.LAPLACIANBLURGRAY_5X5_15X15_SHAVES6,
    shave4.LAPLACIANBLURGRAY_5X5_15X15_SHAVES6,
    shave5.LAPLACIANBLURGRAY_5X5_15X15_SHAVES6,
    shave6.LAPLACIANBLURGRAY_5X5_15X15_SHAVES6,
)

LAPLACIANBLURGRAY_5X5_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_5X5_3X3_SHAVES6,
    shave2.LAPLACIANBLURGRAY_5X5_3X3_SHAVES6,
    shave3.LAPLACIANBLURGRAY_5X5_3X3_SHAVES6,
    shave4.LAPLACIANBLURGRAY_5X5_3X3_SHAVES6,
    shave5.LAPLACIANBLURGRAY_5X5_3X3_SHAVES6,
    shave6.LAPLACIANBLURGRAY_5X5_3X3_SHAVES6,
)

LAPLACIANBLURGRAY_5X5_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_5X5_5X5_SHAVES6,
    shave2.LAPLACIANBLURGRAY_5X5_5X5_SHAVES6,
    shave3.LAPLACIANBLURGRAY_5X5_5X5_SHAVES6,
    shave4.LAPLACIANBLURGRAY_5X5_5X5_SHAVES6,
    shave5.LAPLACIANBLURGRAY_5X5_5X5_SHAVES6,
    shave6.LAPLACIANBLURGRAY_5X5_5X5_SHAVES6,
)

LAPLACIANBLURGRAY_5X5_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_5X5_7X7_SHAVES6,
    shave2.LAPLACIANBLURGRAY_5X5_7X7_SHAVES6,
    shave3.LAPLACIANBLURGRAY_5X5_7X7_SHAVES6,
    shave4.LAPLACIANBLURGRAY_5X5_7X7_SHAVES6,
    shave5.LAPLACIANBLURGRAY_5X5_7X7_SHAVES6,
    shave6.LAPLACIANBLURGRAY_5X5_7X7_SHAVES6,
)

LAPLACIANBLURGRAY_5X5_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_5X5_9X9_SHAVES6,
    shave2.LAPLACIANBLURGRAY_5X5_9X9_SHAVES6,
    shave3.LAPLACIANBLURGRAY_5X5_9X9_SHAVES6,
    shave4.LAPLACIANBLURGRAY_5X5_9X9_SHAVES6,
    shave5.LAPLACIANBLURGRAY_5X5_9X9_SHAVES6,
    shave6.LAPLACIANBLURGRAY_5X5_9X9_SHAVES6,
)

LAPLACIANBLURGRAY_7X7_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_7X7_11X11_SHAVES6,
    shave2.LAPLACIANBLURGRAY_7X7_11X11_SHAVES6,
    shave3.LAPLACIANBLURGRAY_7X7_11X11_SHAVES6,
    shave4.LAPLACIANBLURGRAY_7X7_11X11_SHAVES6,
    shave5.LAPLACIANBLURGRAY_7X7_11X11_SHAVES6,
    shave6.LAPLACIANBLURGRAY_7X7_11X11_SHAVES6,
)

LAPLACIANBLURGRAY_7X7_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_7X7_13X13_SHAVES6,
    shave2.LAPLACIANBLURGRAY_7X7_13X13_SHAVES6,
    shave3.LAPLACIANBLURGRAY_7X7_13X13_SHAVES6,
    shave4.LAPLACIANBLURGRAY_7X7_13X13_SHAVES6,
    shave5.LAPLACIANBLURGRAY_7X7_13X13_SHAVES6,
    shave6.LAPLACIANBLURGRAY_7X7_13X13_SHAVES6,
)

LAPLACIANBLURGRAY_7X7_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_7X7_15X15_SHAVES6,
    shave2.LAPLACIANBLURGRAY_7X7_15X15_SHAVES6,
    shave3.LAPLACIANBLURGRAY_7X7_15X15_SHAVES6,
    shave4.LAPLACIANBLURGRAY_7X7_15X15_SHAVES6,
    shave5.LAPLACIANBLURGRAY_7X7_15X15_SHAVES6,
    shave6.LAPLACIANBLURGRAY_7X7_15X15_SHAVES6,
)

LAPLACIANBLURGRAY_7X7_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_7X7_3X3_SHAVES6,
    shave2.LAPLACIANBLURGRAY_7X7_3X3_SHAVES6,
    shave3.LAPLACIANBLURGRAY_7X7_3X3_SHAVES6,
    shave4.LAPLACIANBLURGRAY_7X7_3X3_SHAVES6,
    shave5.LAPLACIANBLURGRAY_7X7_3X3_SHAVES6,
    shave6.LAPLACIANBLURGRAY_7X7_3X3_SHAVES6,
)

LAPLACIANBLURGRAY_7X7_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_7X7_5X5_SHAVES6,
    shave2.LAPLACIANBLURGRAY_7X7_5X5_SHAVES6,
    shave3.LAPLACIANBLURGRAY_7X7_5X5_SHAVES6,
    shave4.LAPLACIANBLURGRAY_7X7_5X5_SHAVES6,
    shave5.LAPLACIANBLURGRAY_7X7_5X5_SHAVES6,
    shave6.LAPLACIANBLURGRAY_7X7_5X5_SHAVES6,
)

LAPLACIANBLURGRAY_7X7_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_7X7_7X7_SHAVES6,
    shave2.LAPLACIANBLURGRAY_7X7_7X7_SHAVES6,
    shave3.LAPLACIANBLURGRAY_7X7_7X7_SHAVES6,
    shave4.LAPLACIANBLURGRAY_7X7_7X7_SHAVES6,
    shave5.LAPLACIANBLURGRAY_7X7_7X7_SHAVES6,
    shave6.LAPLACIANBLURGRAY_7X7_7X7_SHAVES6,
)

LAPLACIANBLURGRAY_7X7_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_7X7_9X9_SHAVES6,
    shave2.LAPLACIANBLURGRAY_7X7_9X9_SHAVES6,
    shave3.LAPLACIANBLURGRAY_7X7_9X9_SHAVES6,
    shave4.LAPLACIANBLURGRAY_7X7_9X9_SHAVES6,
    shave5.LAPLACIANBLURGRAY_7X7_9X9_SHAVES6,
    shave6.LAPLACIANBLURGRAY_7X7_9X9_SHAVES6,
)

LAPLACIANBLURGRAY_9X9_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_9X9_11X11_SHAVES6,
    shave2.LAPLACIANBLURGRAY_9X9_11X11_SHAVES6,
    shave3.LAPLACIANBLURGRAY_9X9_11X11_SHAVES6,
    shave4.LAPLACIANBLURGRAY_9X9_11X11_SHAVES6,
    shave5.LAPLACIANBLURGRAY_9X9_11X11_SHAVES6,
    shave6.LAPLACIANBLURGRAY_9X9_11X11_SHAVES6,
)

LAPLACIANBLURGRAY_9X9_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_9X9_13X13_SHAVES6,
    shave2.LAPLACIANBLURGRAY_9X9_13X13_SHAVES6,
    shave3.LAPLACIANBLURGRAY_9X9_13X13_SHAVES6,
    shave4.LAPLACIANBLURGRAY_9X9_13X13_SHAVES6,
    shave5.LAPLACIANBLURGRAY_9X9_13X13_SHAVES6,
    shave6.LAPLACIANBLURGRAY_9X9_13X13_SHAVES6,
)

LAPLACIANBLURGRAY_9X9_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_9X9_15X15_SHAVES6,
    shave2.LAPLACIANBLURGRAY_9X9_15X15_SHAVES6,
    shave3.LAPLACIANBLURGRAY_9X9_15X15_SHAVES6,
    shave4.LAPLACIANBLURGRAY_9X9_15X15_SHAVES6,
    shave5.LAPLACIANBLURGRAY_9X9_15X15_SHAVES6,
    shave6.LAPLACIANBLURGRAY_9X9_15X15_SHAVES6,
)

LAPLACIANBLURGRAY_9X9_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_9X9_3X3_SHAVES6,
    shave2.LAPLACIANBLURGRAY_9X9_3X3_SHAVES6,
    shave3.LAPLACIANBLURGRAY_9X9_3X3_SHAVES6,
    shave4.LAPLACIANBLURGRAY_9X9_3X3_SHAVES6,
    shave5.LAPLACIANBLURGRAY_9X9_3X3_SHAVES6,
    shave6.LAPLACIANBLURGRAY_9X9_3X3_SHAVES6,
)

LAPLACIANBLURGRAY_9X9_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_9X9_5X5_SHAVES6,
    shave2.LAPLACIANBLURGRAY_9X9_5X5_SHAVES6,
    shave3.LAPLACIANBLURGRAY_9X9_5X5_SHAVES6,
    shave4.LAPLACIANBLURGRAY_9X9_5X5_SHAVES6,
    shave5.LAPLACIANBLURGRAY_9X9_5X5_SHAVES6,
    shave6.LAPLACIANBLURGRAY_9X9_5X5_SHAVES6,
)

LAPLACIANBLURGRAY_9X9_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_9X9_7X7_SHAVES6,
    shave2.LAPLACIANBLURGRAY_9X9_7X7_SHAVES6,
    shave3.LAPLACIANBLURGRAY_9X9_7X7_SHAVES6,
    shave4.LAPLACIANBLURGRAY_9X9_7X7_SHAVES6,
    shave5.LAPLACIANBLURGRAY_9X9_7X7_SHAVES6,
    shave6.LAPLACIANBLURGRAY_9X9_7X7_SHAVES6,
)

LAPLACIANBLURGRAY_9X9_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLURGRAY_9X9_9X9_SHAVES6,
    shave2.LAPLACIANBLURGRAY_9X9_9X9_SHAVES6,
    shave3.LAPLACIANBLURGRAY_9X9_9X9_SHAVES6,
    shave4.LAPLACIANBLURGRAY_9X9_9X9_SHAVES6,
    shave5.LAPLACIANBLURGRAY_9X9_9X9_SHAVES6,
    shave6.LAPLACIANBLURGRAY_9X9_9X9_SHAVES6,
)

LAPLACIANBLUR_11X11_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_11X11_11X11_SHAVES6,
    shave2.LAPLACIANBLUR_11X11_11X11_SHAVES6,
    shave3.LAPLACIANBLUR_11X11_11X11_SHAVES6,
    shave4.LAPLACIANBLUR_11X11_11X11_SHAVES6,
    shave5.LAPLACIANBLUR_11X11_11X11_SHAVES6,
    shave6.LAPLACIANBLUR_11X11_11X11_SHAVES6,
)

LAPLACIANBLUR_11X11_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_11X11_13X13_SHAVES6,
    shave2.LAPLACIANBLUR_11X11_13X13_SHAVES6,
    shave3.LAPLACIANBLUR_11X11_13X13_SHAVES6,
    shave4.LAPLACIANBLUR_11X11_13X13_SHAVES6,
    shave5.LAPLACIANBLUR_11X11_13X13_SHAVES6,
    shave6.LAPLACIANBLUR_11X11_13X13_SHAVES6,
)

LAPLACIANBLUR_11X11_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_11X11_15X15_SHAVES6,
    shave2.LAPLACIANBLUR_11X11_15X15_SHAVES6,
    shave3.LAPLACIANBLUR_11X11_15X15_SHAVES6,
    shave4.LAPLACIANBLUR_11X11_15X15_SHAVES6,
    shave5.LAPLACIANBLUR_11X11_15X15_SHAVES6,
    shave6.LAPLACIANBLUR_11X11_15X15_SHAVES6,
)

LAPLACIANBLUR_11X11_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_11X11_3X3_SHAVES6,
    shave2.LAPLACIANBLUR_11X11_3X3_SHAVES6,
    shave3.LAPLACIANBLUR_11X11_3X3_SHAVES6,
    shave4.LAPLACIANBLUR_11X11_3X3_SHAVES6,
    shave5.LAPLACIANBLUR_11X11_3X3_SHAVES6,
    shave6.LAPLACIANBLUR_11X11_3X3_SHAVES6,
)

LAPLACIANBLUR_11X11_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_11X11_5X5_SHAVES6,
    shave2.LAPLACIANBLUR_11X11_5X5_SHAVES6,
    shave3.LAPLACIANBLUR_11X11_5X5_SHAVES6,
    shave4.LAPLACIANBLUR_11X11_5X5_SHAVES6,
    shave5.LAPLACIANBLUR_11X11_5X5_SHAVES6,
    shave6.LAPLACIANBLUR_11X11_5X5_SHAVES6,
)

LAPLACIANBLUR_11X11_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_11X11_7X7_SHAVES6,
    shave2.LAPLACIANBLUR_11X11_7X7_SHAVES6,
    shave3.LAPLACIANBLUR_11X11_7X7_SHAVES6,
    shave4.LAPLACIANBLUR_11X11_7X7_SHAVES6,
    shave5.LAPLACIANBLUR_11X11_7X7_SHAVES6,
    shave6.LAPLACIANBLUR_11X11_7X7_SHAVES6,
)

LAPLACIANBLUR_11X11_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_11X11_9X9_SHAVES6,
    shave2.LAPLACIANBLUR_11X11_9X9_SHAVES6,
    shave3.LAPLACIANBLUR_11X11_9X9_SHAVES6,
    shave4.LAPLACIANBLUR_11X11_9X9_SHAVES6,
    shave5.LAPLACIANBLUR_11X11_9X9_SHAVES6,
    shave6.LAPLACIANBLUR_11X11_9X9_SHAVES6,
)

LAPLACIANBLUR_13X13_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_13X13_11X11_SHAVES6,
    shave2.LAPLACIANBLUR_13X13_11X11_SHAVES6,
    shave3.LAPLACIANBLUR_13X13_11X11_SHAVES6,
    shave4.LAPLACIANBLUR_13X13_11X11_SHAVES6,
    shave5.LAPLACIANBLUR_13X13_11X11_SHAVES6,
    shave6.LAPLACIANBLUR_13X13_11X11_SHAVES6,
)

LAPLACIANBLUR_13X13_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_13X13_13X13_SHAVES6,
    shave2.LAPLACIANBLUR_13X13_13X13_SHAVES6,
    shave3.LAPLACIANBLUR_13X13_13X13_SHAVES6,
    shave4.LAPLACIANBLUR_13X13_13X13_SHAVES6,
    shave5.LAPLACIANBLUR_13X13_13X13_SHAVES6,
    shave6.LAPLACIANBLUR_13X13_13X13_SHAVES6,
)

LAPLACIANBLUR_13X13_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_13X13_15X15_SHAVES6,
    shave2.LAPLACIANBLUR_13X13_15X15_SHAVES6,
    shave3.LAPLACIANBLUR_13X13_15X15_SHAVES6,
    shave4.LAPLACIANBLUR_13X13_15X15_SHAVES6,
    shave5.LAPLACIANBLUR_13X13_15X15_SHAVES6,
    shave6.LAPLACIANBLUR_13X13_15X15_SHAVES6,
)

LAPLACIANBLUR_13X13_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_13X13_3X3_SHAVES6,
    shave2.LAPLACIANBLUR_13X13_3X3_SHAVES6,
    shave3.LAPLACIANBLUR_13X13_3X3_SHAVES6,
    shave4.LAPLACIANBLUR_13X13_3X3_SHAVES6,
    shave5.LAPLACIANBLUR_13X13_3X3_SHAVES6,
    shave6.LAPLACIANBLUR_13X13_3X3_SHAVES6,
)

LAPLACIANBLUR_13X13_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_13X13_5X5_SHAVES6,
    shave2.LAPLACIANBLUR_13X13_5X5_SHAVES6,
    shave3.LAPLACIANBLUR_13X13_5X5_SHAVES6,
    shave4.LAPLACIANBLUR_13X13_5X5_SHAVES6,
    shave5.LAPLACIANBLUR_13X13_5X5_SHAVES6,
    shave6.LAPLACIANBLUR_13X13_5X5_SHAVES6,
)

LAPLACIANBLUR_13X13_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_13X13_7X7_SHAVES6,
    shave2.LAPLACIANBLUR_13X13_7X7_SHAVES6,
    shave3.LAPLACIANBLUR_13X13_7X7_SHAVES6,
    shave4.LAPLACIANBLUR_13X13_7X7_SHAVES6,
    shave5.LAPLACIANBLUR_13X13_7X7_SHAVES6,
    shave6.LAPLACIANBLUR_13X13_7X7_SHAVES6,
)

LAPLACIANBLUR_13X13_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_13X13_9X9_SHAVES6,
    shave2.LAPLACIANBLUR_13X13_9X9_SHAVES6,
    shave3.LAPLACIANBLUR_13X13_9X9_SHAVES6,
    shave4.LAPLACIANBLUR_13X13_9X9_SHAVES6,
    shave5.LAPLACIANBLUR_13X13_9X9_SHAVES6,
    shave6.LAPLACIANBLUR_13X13_9X9_SHAVES6,
)

LAPLACIANBLUR_15X15_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_15X15_11X11_SHAVES6,
    shave2.LAPLACIANBLUR_15X15_11X11_SHAVES6,
    shave3.LAPLACIANBLUR_15X15_11X11_SHAVES6,
    shave4.LAPLACIANBLUR_15X15_11X11_SHAVES6,
    shave5.LAPLACIANBLUR_15X15_11X11_SHAVES6,
    shave6.LAPLACIANBLUR_15X15_11X11_SHAVES6,
)

LAPLACIANBLUR_15X15_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_15X15_13X13_SHAVES6,
    shave2.LAPLACIANBLUR_15X15_13X13_SHAVES6,
    shave3.LAPLACIANBLUR_15X15_13X13_SHAVES6,
    shave4.LAPLACIANBLUR_15X15_13X13_SHAVES6,
    shave5.LAPLACIANBLUR_15X15_13X13_SHAVES6,
    shave6.LAPLACIANBLUR_15X15_13X13_SHAVES6,
)

LAPLACIANBLUR_15X15_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_15X15_15X15_SHAVES6,
    shave2.LAPLACIANBLUR_15X15_15X15_SHAVES6,
    shave3.LAPLACIANBLUR_15X15_15X15_SHAVES6,
    shave4.LAPLACIANBLUR_15X15_15X15_SHAVES6,
    shave5.LAPLACIANBLUR_15X15_15X15_SHAVES6,
    shave6.LAPLACIANBLUR_15X15_15X15_SHAVES6,
)

LAPLACIANBLUR_15X15_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_15X15_3X3_SHAVES6,
    shave2.LAPLACIANBLUR_15X15_3X3_SHAVES6,
    shave3.LAPLACIANBLUR_15X15_3X3_SHAVES6,
    shave4.LAPLACIANBLUR_15X15_3X3_SHAVES6,
    shave5.LAPLACIANBLUR_15X15_3X3_SHAVES6,
    shave6.LAPLACIANBLUR_15X15_3X3_SHAVES6,
)

LAPLACIANBLUR_15X15_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_15X15_5X5_SHAVES6,
    shave2.LAPLACIANBLUR_15X15_5X5_SHAVES6,
    shave3.LAPLACIANBLUR_15X15_5X5_SHAVES6,
    shave4.LAPLACIANBLUR_15X15_5X5_SHAVES6,
    shave5.LAPLACIANBLUR_15X15_5X5_SHAVES6,
    shave6.LAPLACIANBLUR_15X15_5X5_SHAVES6,
)

LAPLACIANBLUR_15X15_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_15X15_7X7_SHAVES6,
    shave2.LAPLACIANBLUR_15X15_7X7_SHAVES6,
    shave3.LAPLACIANBLUR_15X15_7X7_SHAVES6,
    shave4.LAPLACIANBLUR_15X15_7X7_SHAVES6,
    shave5.LAPLACIANBLUR_15X15_7X7_SHAVES6,
    shave6.LAPLACIANBLUR_15X15_7X7_SHAVES6,
)

LAPLACIANBLUR_15X15_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_15X15_9X9_SHAVES6,
    shave2.LAPLACIANBLUR_15X15_9X9_SHAVES6,
    shave3.LAPLACIANBLUR_15X15_9X9_SHAVES6,
    shave4.LAPLACIANBLUR_15X15_9X9_SHAVES6,
    shave5.LAPLACIANBLUR_15X15_9X9_SHAVES6,
    shave6.LAPLACIANBLUR_15X15_9X9_SHAVES6,
)

LAPLACIANBLUR_3X3_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_3X3_11X11_SHAVES6,
    shave2.LAPLACIANBLUR_3X3_11X11_SHAVES6,
    shave3.LAPLACIANBLUR_3X3_11X11_SHAVES6,
    shave4.LAPLACIANBLUR_3X3_11X11_SHAVES6,
    shave5.LAPLACIANBLUR_3X3_11X11_SHAVES6,
    shave6.LAPLACIANBLUR_3X3_11X11_SHAVES6,
)

LAPLACIANBLUR_3X3_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_3X3_13X13_SHAVES6,
    shave2.LAPLACIANBLUR_3X3_13X13_SHAVES6,
    shave3.LAPLACIANBLUR_3X3_13X13_SHAVES6,
    shave4.LAPLACIANBLUR_3X3_13X13_SHAVES6,
    shave5.LAPLACIANBLUR_3X3_13X13_SHAVES6,
    shave6.LAPLACIANBLUR_3X3_13X13_SHAVES6,
)

LAPLACIANBLUR_3X3_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_3X3_15X15_SHAVES6,
    shave2.LAPLACIANBLUR_3X3_15X15_SHAVES6,
    shave3.LAPLACIANBLUR_3X3_15X15_SHAVES6,
    shave4.LAPLACIANBLUR_3X3_15X15_SHAVES6,
    shave5.LAPLACIANBLUR_3X3_15X15_SHAVES6,
    shave6.LAPLACIANBLUR_3X3_15X15_SHAVES6,
)

LAPLACIANBLUR_3X3_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_3X3_3X3_SHAVES6,
    shave2.LAPLACIANBLUR_3X3_3X3_SHAVES6,
    shave3.LAPLACIANBLUR_3X3_3X3_SHAVES6,
    shave4.LAPLACIANBLUR_3X3_3X3_SHAVES6,
    shave5.LAPLACIANBLUR_3X3_3X3_SHAVES6,
    shave6.LAPLACIANBLUR_3X3_3X3_SHAVES6,
)

LAPLACIANBLUR_3X3_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_3X3_5X5_SHAVES6,
    shave2.LAPLACIANBLUR_3X3_5X5_SHAVES6,
    shave3.LAPLACIANBLUR_3X3_5X5_SHAVES6,
    shave4.LAPLACIANBLUR_3X3_5X5_SHAVES6,
    shave5.LAPLACIANBLUR_3X3_5X5_SHAVES6,
    shave6.LAPLACIANBLUR_3X3_5X5_SHAVES6,
)

LAPLACIANBLUR_3X3_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_3X3_7X7_SHAVES6,
    shave2.LAPLACIANBLUR_3X3_7X7_SHAVES6,
    shave3.LAPLACIANBLUR_3X3_7X7_SHAVES6,
    shave4.LAPLACIANBLUR_3X3_7X7_SHAVES6,
    shave5.LAPLACIANBLUR_3X3_7X7_SHAVES6,
    shave6.LAPLACIANBLUR_3X3_7X7_SHAVES6,
)

LAPLACIANBLUR_3X3_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_3X3_9X9_SHAVES6,
    shave2.LAPLACIANBLUR_3X3_9X9_SHAVES6,
    shave3.LAPLACIANBLUR_3X3_9X9_SHAVES6,
    shave4.LAPLACIANBLUR_3X3_9X9_SHAVES6,
    shave5.LAPLACIANBLUR_3X3_9X9_SHAVES6,
    shave6.LAPLACIANBLUR_3X3_9X9_SHAVES6,
)

LAPLACIANBLUR_5X5_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_5X5_11X11_SHAVES6,
    shave2.LAPLACIANBLUR_5X5_11X11_SHAVES6,
    shave3.LAPLACIANBLUR_5X5_11X11_SHAVES6,
    shave4.LAPLACIANBLUR_5X5_11X11_SHAVES6,
    shave5.LAPLACIANBLUR_5X5_11X11_SHAVES6,
    shave6.LAPLACIANBLUR_5X5_11X11_SHAVES6,
)

LAPLACIANBLUR_5X5_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_5X5_13X13_SHAVES6,
    shave2.LAPLACIANBLUR_5X5_13X13_SHAVES6,
    shave3.LAPLACIANBLUR_5X5_13X13_SHAVES6,
    shave4.LAPLACIANBLUR_5X5_13X13_SHAVES6,
    shave5.LAPLACIANBLUR_5X5_13X13_SHAVES6,
    shave6.LAPLACIANBLUR_5X5_13X13_SHAVES6,
)

LAPLACIANBLUR_5X5_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_5X5_15X15_SHAVES6,
    shave2.LAPLACIANBLUR_5X5_15X15_SHAVES6,
    shave3.LAPLACIANBLUR_5X5_15X15_SHAVES6,
    shave4.LAPLACIANBLUR_5X5_15X15_SHAVES6,
    shave5.LAPLACIANBLUR_5X5_15X15_SHAVES6,
    shave6.LAPLACIANBLUR_5X5_15X15_SHAVES6,
)

LAPLACIANBLUR_5X5_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_5X5_3X3_SHAVES6,
    shave2.LAPLACIANBLUR_5X5_3X3_SHAVES6,
    shave3.LAPLACIANBLUR_5X5_3X3_SHAVES6,
    shave4.LAPLACIANBLUR_5X5_3X3_SHAVES6,
    shave5.LAPLACIANBLUR_5X5_3X3_SHAVES6,
    shave6.LAPLACIANBLUR_5X5_3X3_SHAVES6,
)

LAPLACIANBLUR_5X5_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_5X5_5X5_SHAVES6,
    shave2.LAPLACIANBLUR_5X5_5X5_SHAVES6,
    shave3.LAPLACIANBLUR_5X5_5X5_SHAVES6,
    shave4.LAPLACIANBLUR_5X5_5X5_SHAVES6,
    shave5.LAPLACIANBLUR_5X5_5X5_SHAVES6,
    shave6.LAPLACIANBLUR_5X5_5X5_SHAVES6,
)

LAPLACIANBLUR_5X5_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_5X5_7X7_SHAVES6,
    shave2.LAPLACIANBLUR_5X5_7X7_SHAVES6,
    shave3.LAPLACIANBLUR_5X5_7X7_SHAVES6,
    shave4.LAPLACIANBLUR_5X5_7X7_SHAVES6,
    shave5.LAPLACIANBLUR_5X5_7X7_SHAVES6,
    shave6.LAPLACIANBLUR_5X5_7X7_SHAVES6,
)

LAPLACIANBLUR_5X5_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_5X5_9X9_SHAVES6,
    shave2.LAPLACIANBLUR_5X5_9X9_SHAVES6,
    shave3.LAPLACIANBLUR_5X5_9X9_SHAVES6,
    shave4.LAPLACIANBLUR_5X5_9X9_SHAVES6,
    shave5.LAPLACIANBLUR_5X5_9X9_SHAVES6,
    shave6.LAPLACIANBLUR_5X5_9X9_SHAVES6,
)

LAPLACIANBLUR_7X7_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_7X7_11X11_SHAVES6,
    shave2.LAPLACIANBLUR_7X7_11X11_SHAVES6,
    shave3.LAPLACIANBLUR_7X7_11X11_SHAVES6,
    shave4.LAPLACIANBLUR_7X7_11X11_SHAVES6,
    shave5.LAPLACIANBLUR_7X7_11X11_SHAVES6,
    shave6.LAPLACIANBLUR_7X7_11X11_SHAVES6,
)

LAPLACIANBLUR_7X7_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_7X7_13X13_SHAVES6,
    shave2.LAPLACIANBLUR_7X7_13X13_SHAVES6,
    shave3.LAPLACIANBLUR_7X7_13X13_SHAVES6,
    shave4.LAPLACIANBLUR_7X7_13X13_SHAVES6,
    shave5.LAPLACIANBLUR_7X7_13X13_SHAVES6,
    shave6.LAPLACIANBLUR_7X7_13X13_SHAVES6,
)

LAPLACIANBLUR_7X7_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_7X7_15X15_SHAVES6,
    shave2.LAPLACIANBLUR_7X7_15X15_SHAVES6,
    shave3.LAPLACIANBLUR_7X7_15X15_SHAVES6,
    shave4.LAPLACIANBLUR_7X7_15X15_SHAVES6,
    shave5.LAPLACIANBLUR_7X7_15X15_SHAVES6,
    shave6.LAPLACIANBLUR_7X7_15X15_SHAVES6,
)

LAPLACIANBLUR_7X7_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_7X7_3X3_SHAVES6,
    shave2.LAPLACIANBLUR_7X7_3X3_SHAVES6,
    shave3.LAPLACIANBLUR_7X7_3X3_SHAVES6,
    shave4.LAPLACIANBLUR_7X7_3X3_SHAVES6,
    shave5.LAPLACIANBLUR_7X7_3X3_SHAVES6,
    shave6.LAPLACIANBLUR_7X7_3X3_SHAVES6,
)

LAPLACIANBLUR_7X7_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_7X7_5X5_SHAVES6,
    shave2.LAPLACIANBLUR_7X7_5X5_SHAVES6,
    shave3.LAPLACIANBLUR_7X7_5X5_SHAVES6,
    shave4.LAPLACIANBLUR_7X7_5X5_SHAVES6,
    shave5.LAPLACIANBLUR_7X7_5X5_SHAVES6,
    shave6.LAPLACIANBLUR_7X7_5X5_SHAVES6,
)

LAPLACIANBLUR_7X7_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_7X7_7X7_SHAVES6,
    shave2.LAPLACIANBLUR_7X7_7X7_SHAVES6,
    shave3.LAPLACIANBLUR_7X7_7X7_SHAVES6,
    shave4.LAPLACIANBLUR_7X7_7X7_SHAVES6,
    shave5.LAPLACIANBLUR_7X7_7X7_SHAVES6,
    shave6.LAPLACIANBLUR_7X7_7X7_SHAVES6,
)

LAPLACIANBLUR_7X7_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_7X7_9X9_SHAVES6,
    shave2.LAPLACIANBLUR_7X7_9X9_SHAVES6,
    shave3.LAPLACIANBLUR_7X7_9X9_SHAVES6,
    shave4.LAPLACIANBLUR_7X7_9X9_SHAVES6,
    shave5.LAPLACIANBLUR_7X7_9X9_SHAVES6,
    shave6.LAPLACIANBLUR_7X7_9X9_SHAVES6,
)

LAPLACIANBLUR_9X9_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_9X9_11X11_SHAVES6,
    shave2.LAPLACIANBLUR_9X9_11X11_SHAVES6,
    shave3.LAPLACIANBLUR_9X9_11X11_SHAVES6,
    shave4.LAPLACIANBLUR_9X9_11X11_SHAVES6,
    shave5.LAPLACIANBLUR_9X9_11X11_SHAVES6,
    shave6.LAPLACIANBLUR_9X9_11X11_SHAVES6,
)

LAPLACIANBLUR_9X9_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_9X9_13X13_SHAVES6,
    shave2.LAPLACIANBLUR_9X9_13X13_SHAVES6,
    shave3.LAPLACIANBLUR_9X9_13X13_SHAVES6,
    shave4.LAPLACIANBLUR_9X9_13X13_SHAVES6,
    shave5.LAPLACIANBLUR_9X9_13X13_SHAVES6,
    shave6.LAPLACIANBLUR_9X9_13X13_SHAVES6,
)

LAPLACIANBLUR_9X9_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_9X9_15X15_SHAVES6,
    shave2.LAPLACIANBLUR_9X9_15X15_SHAVES6,
    shave3.LAPLACIANBLUR_9X9_15X15_SHAVES6,
    shave4.LAPLACIANBLUR_9X9_15X15_SHAVES6,
    shave5.LAPLACIANBLUR_9X9_15X15_SHAVES6,
    shave6.LAPLACIANBLUR_9X9_15X15_SHAVES6,
)

LAPLACIANBLUR_9X9_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_9X9_3X3_SHAVES6,
    shave2.LAPLACIANBLUR_9X9_3X3_SHAVES6,
    shave3.LAPLACIANBLUR_9X9_3X3_SHAVES6,
    shave4.LAPLACIANBLUR_9X9_3X3_SHAVES6,
    shave5.LAPLACIANBLUR_9X9_3X3_SHAVES6,
    shave6.LAPLACIANBLUR_9X9_3X3_SHAVES6,
)

LAPLACIANBLUR_9X9_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_9X9_5X5_SHAVES6,
    shave2.LAPLACIANBLUR_9X9_5X5_SHAVES6,
    shave3.LAPLACIANBLUR_9X9_5X5_SHAVES6,
    shave4.LAPLACIANBLUR_9X9_5X5_SHAVES6,
    shave5.LAPLACIANBLUR_9X9_5X5_SHAVES6,
    shave6.LAPLACIANBLUR_9X9_5X5_SHAVES6,
)

LAPLACIANBLUR_9X9_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_9X9_7X7_SHAVES6,
    shave2.LAPLACIANBLUR_9X9_7X7_SHAVES6,
    shave3.LAPLACIANBLUR_9X9_7X7_SHAVES6,
    shave4.LAPLACIANBLUR_9X9_7X7_SHAVES6,
    shave5.LAPLACIANBLUR_9X9_7X7_SHAVES6,
    shave6.LAPLACIANBLUR_9X9_7X7_SHAVES6,
)

LAPLACIANBLUR_9X9_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANBLUR_9X9_9X9_SHAVES6,
    shave2.LAPLACIANBLUR_9X9_9X9_SHAVES6,
    shave3.LAPLACIANBLUR_9X9_9X9_SHAVES6,
    shave4.LAPLACIANBLUR_9X9_9X9_SHAVES6,
    shave5.LAPLACIANBLUR_9X9_9X9_SHAVES6,
    shave6.LAPLACIANBLUR_9X9_9X9_SHAVES6,
)

LAPLACIANGRAY_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANGRAY_11X11_SHAVES6,
    shave2.LAPLACIANGRAY_11X11_SHAVES6,
    shave3.LAPLACIANGRAY_11X11_SHAVES6,
    shave4.LAPLACIANGRAY_11X11_SHAVES6,
    shave5.LAPLACIANGRAY_11X11_SHAVES6,
    shave6.LAPLACIANGRAY_11X11_SHAVES6,
)

LAPLACIANGRAY_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANGRAY_13X13_SHAVES6,
    shave2.LAPLACIANGRAY_13X13_SHAVES6,
    shave3.LAPLACIANGRAY_13X13_SHAVES6,
    shave4.LAPLACIANGRAY_13X13_SHAVES6,
    shave5.LAPLACIANGRAY_13X13_SHAVES6,
    shave6.LAPLACIANGRAY_13X13_SHAVES6,
)

LAPLACIANGRAY_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANGRAY_15X15_SHAVES6,
    shave2.LAPLACIANGRAY_15X15_SHAVES6,
    shave3.LAPLACIANGRAY_15X15_SHAVES6,
    shave4.LAPLACIANGRAY_15X15_SHAVES6,
    shave5.LAPLACIANGRAY_15X15_SHAVES6,
    shave6.LAPLACIANGRAY_15X15_SHAVES6,
)

LAPLACIANGRAY_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANGRAY_3X3_SHAVES6,
    shave2.LAPLACIANGRAY_3X3_SHAVES6,
    shave3.LAPLACIANGRAY_3X3_SHAVES6,
    shave4.LAPLACIANGRAY_3X3_SHAVES6,
    shave5.LAPLACIANGRAY_3X3_SHAVES6,
    shave6.LAPLACIANGRAY_3X3_SHAVES6,
)

LAPLACIANGRAY_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANGRAY_5X5_SHAVES6,
    shave2.LAPLACIANGRAY_5X5_SHAVES6,
    shave3.LAPLACIANGRAY_5X5_SHAVES6,
    shave4.LAPLACIANGRAY_5X5_SHAVES6,
    shave5.LAPLACIANGRAY_5X5_SHAVES6,
    shave6.LAPLACIANGRAY_5X5_SHAVES6,
)

LAPLACIANGRAY_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANGRAY_7X7_SHAVES6,
    shave2.LAPLACIANGRAY_7X7_SHAVES6,
    shave3.LAPLACIANGRAY_7X7_SHAVES6,
    shave4.LAPLACIANGRAY_7X7_SHAVES6,
    shave5.LAPLACIANGRAY_7X7_SHAVES6,
    shave6.LAPLACIANGRAY_7X7_SHAVES6,
)

LAPLACIANGRAY_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIANGRAY_9X9_SHAVES6,
    shave2.LAPLACIANGRAY_9X9_SHAVES6,
    shave3.LAPLACIANGRAY_9X9_SHAVES6,
    shave4.LAPLACIANGRAY_9X9_SHAVES6,
    shave5.LAPLACIANGRAY_9X9_SHAVES6,
    shave6.LAPLACIANGRAY_9X9_SHAVES6,
)

LAPLACIAN_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIAN_11X11_SHAVES6,
    shave2.LAPLACIAN_11X11_SHAVES6,
    shave3.LAPLACIAN_11X11_SHAVES6,
    shave4.LAPLACIAN_11X11_SHAVES6,
    shave5.LAPLACIAN_11X11_SHAVES6,
    shave6.LAPLACIAN_11X11_SHAVES6,
)

LAPLACIAN_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIAN_13X13_SHAVES6,
    shave2.LAPLACIAN_13X13_SHAVES6,
    shave3.LAPLACIAN_13X13_SHAVES6,
    shave4.LAPLACIAN_13X13_SHAVES6,
    shave5.LAPLACIAN_13X13_SHAVES6,
    shave6.LAPLACIAN_13X13_SHAVES6,
)

LAPLACIAN_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIAN_15X15_SHAVES6,
    shave2.LAPLACIAN_15X15_SHAVES6,
    shave3.LAPLACIAN_15X15_SHAVES6,
    shave4.LAPLACIAN_15X15_SHAVES6,
    shave5.LAPLACIAN_15X15_SHAVES6,
    shave6.LAPLACIAN_15X15_SHAVES6,
)

LAPLACIAN_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIAN_3X3_SHAVES6,
    shave2.LAPLACIAN_3X3_SHAVES6,
    shave3.LAPLACIAN_3X3_SHAVES6,
    shave4.LAPLACIAN_3X3_SHAVES6,
    shave5.LAPLACIAN_3X3_SHAVES6,
    shave6.LAPLACIAN_3X3_SHAVES6,
)

LAPLACIAN_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIAN_5X5_SHAVES6,
    shave2.LAPLACIAN_5X5_SHAVES6,
    shave3.LAPLACIAN_5X5_SHAVES6,
    shave4.LAPLACIAN_5X5_SHAVES6,
    shave5.LAPLACIAN_5X5_SHAVES6,
    shave6.LAPLACIAN_5X5_SHAVES6,
)

LAPLACIAN_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIAN_7X7_SHAVES6,
    shave2.LAPLACIAN_7X7_SHAVES6,
    shave3.LAPLACIAN_7X7_SHAVES6,
    shave4.LAPLACIAN_7X7_SHAVES6,
    shave5.LAPLACIAN_7X7_SHAVES6,
    shave6.LAPLACIAN_7X7_SHAVES6,
)

LAPLACIAN_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.LAPLACIAN_9X9_SHAVES6,
    shave2.LAPLACIAN_9X9_SHAVES6,
    shave3.LAPLACIAN_9X9_SHAVES6,
    shave4.LAPLACIAN_9X9_SHAVES6,
    shave5.LAPLACIAN_9X9_SHAVES6,
    shave6.LAPLACIAN_9X9_SHAVES6,
)

LASERSCAN_10_1_SHAVES6: tuple[Path, ...] = (
    shave1.LASERSCAN_10_1_SHAVES6,
    shave2.LASERSCAN_10_1_SHAVES6,
    shave3.LASERSCAN_10_1_SHAVES6,
    shave4.LASERSCAN_10_1_SHAVES6,
    shave5.LASERSCAN_10_1_SHAVES6,
    shave6.LASERSCAN_10_1_SHAVES6,
)

LASERSCAN_10_3_SHAVES6: tuple[Path, ...] = (
    shave1.LASERSCAN_10_3_SHAVES6,
    shave2.LASERSCAN_10_3_SHAVES6,
    shave3.LASERSCAN_10_3_SHAVES6,
    shave4.LASERSCAN_10_3_SHAVES6,
    shave5.LASERSCAN_10_3_SHAVES6,
    shave6.LASERSCAN_10_3_SHAVES6,
)

LASERSCAN_10_5_SHAVES6: tuple[Path, ...] = (
    shave1.LASERSCAN_10_5_SHAVES6,
    shave2.LASERSCAN_10_5_SHAVES6,
    shave3.LASERSCAN_10_5_SHAVES6,
    shave4.LASERSCAN_10_5_SHAVES6,
    shave5.LASERSCAN_10_5_SHAVES6,
    shave6.LASERSCAN_10_5_SHAVES6,
)

LASERSCAN_20_1_SHAVES6: tuple[Path, ...] = (
    shave1.LASERSCAN_20_1_SHAVES6,
    shave2.LASERSCAN_20_1_SHAVES6,
    shave3.LASERSCAN_20_1_SHAVES6,
    shave4.LASERSCAN_20_1_SHAVES6,
    shave5.LASERSCAN_20_1_SHAVES6,
    shave6.LASERSCAN_20_1_SHAVES6,
)

LASERSCAN_20_3_SHAVES6: tuple[Path, ...] = (
    shave1.LASERSCAN_20_3_SHAVES6,
    shave2.LASERSCAN_20_3_SHAVES6,
    shave3.LASERSCAN_20_3_SHAVES6,
    shave4.LASERSCAN_20_3_SHAVES6,
    shave5.LASERSCAN_20_3_SHAVES6,
    shave6.LASERSCAN_20_3_SHAVES6,
)

LASERSCAN_20_5_SHAVES6: tuple[Path, ...] = (
    shave1.LASERSCAN_20_5_SHAVES6,
    shave2.LASERSCAN_20_5_SHAVES6,
    shave3.LASERSCAN_20_5_SHAVES6,
    shave4.LASERSCAN_20_5_SHAVES6,
    shave5.LASERSCAN_20_5_SHAVES6,
    shave6.LASERSCAN_20_5_SHAVES6,
)

LASERSCAN_5_1_SHAVES6: tuple[Path, ...] = (
    shave1.LASERSCAN_5_1_SHAVES6,
    shave2.LASERSCAN_5_1_SHAVES6,
    shave3.LASERSCAN_5_1_SHAVES6,
    shave4.LASERSCAN_5_1_SHAVES6,
    shave5.LASERSCAN_5_1_SHAVES6,
    shave6.LASERSCAN_5_1_SHAVES6,
)

LASERSCAN_5_3_SHAVES6: tuple[Path, ...] = (
    shave1.LASERSCAN_5_3_SHAVES6,
    shave2.LASERSCAN_5_3_SHAVES6,
    shave3.LASERSCAN_5_3_SHAVES6,
    shave4.LASERSCAN_5_3_SHAVES6,
    shave5.LASERSCAN_5_3_SHAVES6,
    shave6.LASERSCAN_5_3_SHAVES6,
)

LASERSCAN_5_5_SHAVES6: tuple[Path, ...] = (
    shave1.LASERSCAN_5_5_SHAVES6,
    shave2.LASERSCAN_5_5_SHAVES6,
    shave3.LASERSCAN_5_5_SHAVES6,
    shave4.LASERSCAN_5_5_SHAVES6,
    shave5.LASERSCAN_5_5_SHAVES6,
    shave6.LASERSCAN_5_5_SHAVES6,
)

POINTCLOUD_SHAVES6: tuple[Path, ...] = (
    shave1.POINTCLOUD_SHAVES6,
    shave2.POINTCLOUD_SHAVES6,
    shave3.POINTCLOUD_SHAVES6,
    shave4.POINTCLOUD_SHAVES6,
    shave5.POINTCLOUD_SHAVES6,
    shave6.POINTCLOUD_SHAVES6,
)

SOBELBLURGRAY_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLURGRAY_11X11_SHAVES6,
    shave2.SOBELBLURGRAY_11X11_SHAVES6,
    shave3.SOBELBLURGRAY_11X11_SHAVES6,
    shave4.SOBELBLURGRAY_11X11_SHAVES6,
    shave5.SOBELBLURGRAY_11X11_SHAVES6,
    shave6.SOBELBLURGRAY_11X11_SHAVES6,
)

SOBELBLURGRAY_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLURGRAY_13X13_SHAVES6,
    shave2.SOBELBLURGRAY_13X13_SHAVES6,
    shave3.SOBELBLURGRAY_13X13_SHAVES6,
    shave4.SOBELBLURGRAY_13X13_SHAVES6,
    shave5.SOBELBLURGRAY_13X13_SHAVES6,
    shave6.SOBELBLURGRAY_13X13_SHAVES6,
)

SOBELBLURGRAY_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLURGRAY_15X15_SHAVES6,
    shave2.SOBELBLURGRAY_15X15_SHAVES6,
    shave3.SOBELBLURGRAY_15X15_SHAVES6,
    shave4.SOBELBLURGRAY_15X15_SHAVES6,
    shave5.SOBELBLURGRAY_15X15_SHAVES6,
    shave6.SOBELBLURGRAY_15X15_SHAVES6,
)

SOBELBLURGRAY_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLURGRAY_3X3_SHAVES6,
    shave2.SOBELBLURGRAY_3X3_SHAVES6,
    shave3.SOBELBLURGRAY_3X3_SHAVES6,
    shave4.SOBELBLURGRAY_3X3_SHAVES6,
    shave5.SOBELBLURGRAY_3X3_SHAVES6,
    shave6.SOBELBLURGRAY_3X3_SHAVES6,
)

SOBELBLURGRAY_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLURGRAY_5X5_SHAVES6,
    shave2.SOBELBLURGRAY_5X5_SHAVES6,
    shave3.SOBELBLURGRAY_5X5_SHAVES6,
    shave4.SOBELBLURGRAY_5X5_SHAVES6,
    shave5.SOBELBLURGRAY_5X5_SHAVES6,
    shave6.SOBELBLURGRAY_5X5_SHAVES6,
)

SOBELBLURGRAY_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLURGRAY_7X7_SHAVES6,
    shave2.SOBELBLURGRAY_7X7_SHAVES6,
    shave3.SOBELBLURGRAY_7X7_SHAVES6,
    shave4.SOBELBLURGRAY_7X7_SHAVES6,
    shave5.SOBELBLURGRAY_7X7_SHAVES6,
    shave6.SOBELBLURGRAY_7X7_SHAVES6,
)

SOBELBLURGRAY_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLURGRAY_9X9_SHAVES6,
    shave2.SOBELBLURGRAY_9X9_SHAVES6,
    shave3.SOBELBLURGRAY_9X9_SHAVES6,
    shave4.SOBELBLURGRAY_9X9_SHAVES6,
    shave5.SOBELBLURGRAY_9X9_SHAVES6,
    shave6.SOBELBLURGRAY_9X9_SHAVES6,
)

SOBELBLUR_11X11_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLUR_11X11_SHAVES6,
    shave2.SOBELBLUR_11X11_SHAVES6,
    shave3.SOBELBLUR_11X11_SHAVES6,
    shave4.SOBELBLUR_11X11_SHAVES6,
    shave5.SOBELBLUR_11X11_SHAVES6,
    shave6.SOBELBLUR_11X11_SHAVES6,
)

SOBELBLUR_13X13_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLUR_13X13_SHAVES6,
    shave2.SOBELBLUR_13X13_SHAVES6,
    shave3.SOBELBLUR_13X13_SHAVES6,
    shave4.SOBELBLUR_13X13_SHAVES6,
    shave5.SOBELBLUR_13X13_SHAVES6,
    shave6.SOBELBLUR_13X13_SHAVES6,
)

SOBELBLUR_15X15_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLUR_15X15_SHAVES6,
    shave2.SOBELBLUR_15X15_SHAVES6,
    shave3.SOBELBLUR_15X15_SHAVES6,
    shave4.SOBELBLUR_15X15_SHAVES6,
    shave5.SOBELBLUR_15X15_SHAVES6,
    shave6.SOBELBLUR_15X15_SHAVES6,
)

SOBELBLUR_3X3_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLUR_3X3_SHAVES6,
    shave2.SOBELBLUR_3X3_SHAVES6,
    shave3.SOBELBLUR_3X3_SHAVES6,
    shave4.SOBELBLUR_3X3_SHAVES6,
    shave5.SOBELBLUR_3X3_SHAVES6,
    shave6.SOBELBLUR_3X3_SHAVES6,
)

SOBELBLUR_5X5_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLUR_5X5_SHAVES6,
    shave2.SOBELBLUR_5X5_SHAVES6,
    shave3.SOBELBLUR_5X5_SHAVES6,
    shave4.SOBELBLUR_5X5_SHAVES6,
    shave5.SOBELBLUR_5X5_SHAVES6,
    shave6.SOBELBLUR_5X5_SHAVES6,
)

SOBELBLUR_7X7_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLUR_7X7_SHAVES6,
    shave2.SOBELBLUR_7X7_SHAVES6,
    shave3.SOBELBLUR_7X7_SHAVES6,
    shave4.SOBELBLUR_7X7_SHAVES6,
    shave5.SOBELBLUR_7X7_SHAVES6,
    shave6.SOBELBLUR_7X7_SHAVES6,
)

SOBELBLUR_9X9_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELBLUR_9X9_SHAVES6,
    shave2.SOBELBLUR_9X9_SHAVES6,
    shave3.SOBELBLUR_9X9_SHAVES6,
    shave4.SOBELBLUR_9X9_SHAVES6,
    shave5.SOBELBLUR_9X9_SHAVES6,
    shave6.SOBELBLUR_9X9_SHAVES6,
)

SOBELGRAY_SHAVES6: tuple[Path, ...] = (
    shave1.SOBELGRAY_SHAVES6,
    shave2.SOBELGRAY_SHAVES6,
    shave3.SOBELGRAY_SHAVES6,
    shave4.SOBELGRAY_SHAVES6,
    shave5.SOBELGRAY_SHAVES6,
    shave6.SOBELGRAY_SHAVES6,
)

SOBEL_SHAVES6: tuple[Path, ...] = (
    shave1.SOBEL_SHAVES6,
    shave2.SOBEL_SHAVES6,
    shave3.SOBEL_SHAVES6,
    shave4.SOBEL_SHAVES6,
    shave5.SOBEL_SHAVES6,
    shave6.SOBEL_SHAVES6,
)

