"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from open3d.cpu import pybind as pybind
from open3d.cpu.pybind import camera as camera, core as core, data as data, geometry as geometry, io as io, pipelines as pipelines, t as t, utility as utility

"""
This type stub file was generated by pyright.
"""
def load_cdll(path):
    ...

__DEVICE_API__: str
__version__: str
shell: Incomplete
