# This file is auto-generated by models/generate.py

import os

_BLOB_FOLDER = "blobs"

GAUSSIAN_11X11 = os.path.join(_BLOB_FOLDER, "gaussian_11x11.blob")
GAUSSIAN_13X13 = os.path.join(_BLOB_FOLDER, "gaussian_13x13.blob")
GAUSSIAN_15X15 = os.path.join(_BLOB_FOLDER, "gaussian_15x15.blob")
GAUSSIAN_3X3 = os.path.join(_BLOB_FOLDER, "gaussian_3x3.blob")
GAUSSIAN_5X5 = os.path.join(_BLOB_FOLDER, "gaussian_5x5.blob")
GAUSSIAN_7X7 = os.path.join(_BLOB_FOLDER, "gaussian_7x7.blob")
GAUSSIAN_9X9 = os.path.join(_BLOB_FOLDER, "gaussian_9x9.blob")
LAPLACIAN_11X11 = os.path.join(_BLOB_FOLDER, "laplacian_11x11.blob")
LAPLACIAN_13X13 = os.path.join(_BLOB_FOLDER, "laplacian_13x13.blob")
LAPLACIAN_15X15 = os.path.join(_BLOB_FOLDER, "laplacian_15x15.blob")
LAPLACIAN_3X3 = os.path.join(_BLOB_FOLDER, "laplacian_3x3.blob")
LAPLACIAN_5X5 = os.path.join(_BLOB_FOLDER, "laplacian_5x5.blob")
LAPLACIAN_7X7 = os.path.join(_BLOB_FOLDER, "laplacian_7x7.blob")
LAPLACIAN_9X9 = os.path.join(_BLOB_FOLDER, "laplacian_9x9.blob")
SOBEL = os.path.join(_BLOB_FOLDER, "sobel.blob")
SOBEL_BLUR_11X11 = os.path.join(_BLOB_FOLDER, "sobel_blur_11x11.blob")
SOBEL_BLUR_13X13 = os.path.join(_BLOB_FOLDER, "sobel_blur_13x13.blob")
SOBEL_BLUR_15X15 = os.path.join(_BLOB_FOLDER, "sobel_blur_15x15.blob")
SOBEL_BLUR_3X3 = os.path.join(_BLOB_FOLDER, "sobel_blur_3x3.blob")
SOBEL_BLUR_5X5 = os.path.join(_BLOB_FOLDER, "sobel_blur_5x5.blob")
SOBEL_BLUR_7X7 = os.path.join(_BLOB_FOLDER, "sobel_blur_7x7.blob")
SOBEL_BLUR_9X9 = os.path.join(_BLOB_FOLDER, "sobel_blur_9x9.blob")

__all__ = [
    "GAUSSIAN_11X11",
    "GAUSSIAN_13X13",
    "GAUSSIAN_15X15",
    "GAUSSIAN_3X3",
    "GAUSSIAN_5X5",
    "GAUSSIAN_7X7",
    "GAUSSIAN_9X9",
    "LAPLACIAN_11X11",
    "LAPLACIAN_13X13",
    "LAPLACIAN_15X15",
    "LAPLACIAN_3X3",
    "LAPLACIAN_5X5",
    "LAPLACIAN_7X7",
    "LAPLACIAN_9X9",
    "SOBEL",
    "SOBEL_BLUR_11X11",
    "SOBEL_BLUR_13X13",
    "SOBEL_BLUR_15X15",
    "SOBEL_BLUR_3X3",
    "SOBEL_BLUR_5X5",
    "SOBEL_BLUR_7X7",
    "SOBEL_BLUR_9X9",
]
