# This file is auto-generated by models/generate.py

import os
import sysconfig

_RELATIVE_BLOB_FOLDER = os.path.join('oakutils', 'blobs')
_SITE_PACKAGES = sysconfig.get_paths()['purelib']
_BLOB_FOLDER = os.path.join(_SITE_PACKAGES, _RELATIVE_BLOB_FOLDER)

GAUSSIAN_11X11 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_11x11.blob'))
GAUSSIAN_13X13 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_13x13.blob'))
GAUSSIAN_15X15 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_15x15.blob'))
GAUSSIAN_3X3 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_3x3.blob'))
GAUSSIAN_5X5 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_5x5.blob'))
GAUSSIAN_7X7 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_7x7.blob'))
GAUSSIAN_9X9 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_9x9.blob'))
GAUSSIAN_GRAY_11X11 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_gray_11x11.blob'))
GAUSSIAN_GRAY_13X13 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_gray_13x13.blob'))
GAUSSIAN_GRAY_15X15 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_gray_15x15.blob'))
GAUSSIAN_GRAY_3X3 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_gray_3x3.blob'))
GAUSSIAN_GRAY_5X5 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_gray_5x5.blob'))
GAUSSIAN_GRAY_7X7 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_gray_7x7.blob'))
GAUSSIAN_GRAY_9X9 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_gaussian_gray_9x9.blob'))
LAPLACIAN_11X11 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_11x11.blob'))
LAPLACIAN_13X13 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_13x13.blob'))
LAPLACIAN_15X15 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_15x15.blob'))
LAPLACIAN_3X3 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_3x3.blob'))
LAPLACIAN_5X5 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_5x5.blob'))
LAPLACIAN_7X7 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_7x7.blob'))
LAPLACIAN_9X9 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_9x9.blob'))
LAPLACIAN_GRAY_11X11 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_gray_11x11.blob'))
LAPLACIAN_GRAY_13X13 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_gray_13x13.blob'))
LAPLACIAN_GRAY_15X15 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_gray_15x15.blob'))
LAPLACIAN_GRAY_3X3 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_gray_3x3.blob'))
LAPLACIAN_GRAY_5X5 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_gray_5x5.blob'))
LAPLACIAN_GRAY_7X7 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_gray_7x7.blob'))
LAPLACIAN_GRAY_9X9 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_laplacian_gray_9x9.blob'))
SOBEL = os.path.abspath(os.path.join(_BLOB_FOLDER, '_sobel.blob'))
SOBEL_BLUR_11X11 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_sobel_blur_11x11.blob'))
SOBEL_BLUR_13X13 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_sobel_blur_13x13.blob'))
SOBEL_BLUR_15X15 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_sobel_blur_15x15.blob'))
SOBEL_BLUR_3X3 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_sobel_blur_3x3.blob'))
SOBEL_BLUR_5X5 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_sobel_blur_5x5.blob'))
SOBEL_BLUR_7X7 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_sobel_blur_7x7.blob'))
SOBEL_BLUR_9X9 = os.path.abspath(os.path.join(_BLOB_FOLDER, '_sobel_blur_9x9.blob'))

__all__ = [
    'GAUSSIAN_11X11',
    'GAUSSIAN_13X13',
    'GAUSSIAN_15X15',
    'GAUSSIAN_3X3',
    'GAUSSIAN_5X5',
    'GAUSSIAN_7X7',
    'GAUSSIAN_9X9',
    'GAUSSIAN_GRAY_11X11',
    'GAUSSIAN_GRAY_13X13',
    'GAUSSIAN_GRAY_15X15',
    'GAUSSIAN_GRAY_3X3',
    'GAUSSIAN_GRAY_5X5',
    'GAUSSIAN_GRAY_7X7',
    'GAUSSIAN_GRAY_9X9',
    'LAPLACIAN_11X11',
    'LAPLACIAN_13X13',
    'LAPLACIAN_15X15',
    'LAPLACIAN_3X3',
    'LAPLACIAN_5X5',
    'LAPLACIAN_7X7',
    'LAPLACIAN_9X9',
    'LAPLACIAN_GRAY_11X11',
    'LAPLACIAN_GRAY_13X13',
    'LAPLACIAN_GRAY_15X15',
    'LAPLACIAN_GRAY_3X3',
    'LAPLACIAN_GRAY_5X5',
    'LAPLACIAN_GRAY_7X7',
    'LAPLACIAN_GRAY_9X9',
    'SOBEL',
    'SOBEL_BLUR_11X11',
    'SOBEL_BLUR_13X13',
    'SOBEL_BLUR_15X15',
    'SOBEL_BLUR_3X3',
    'SOBEL_BLUR_5X5',
    'SOBEL_BLUR_7X7',
    'SOBEL_BLUR_9X9',
]
