name: MyPy
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip3 install torch==1.10.2+cpu torchvision==0.11.3+cpu torchaudio==0.10.2+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
          pip install .[dev]
          pip install mypy<1.11.0
          pip install types-setuptools
          pip install types-requests

      - name: Run MyPy check
        run: 
          python3 -m mypy src/oakutils --config-file=pyproject.toml
