name: MyPy Check
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install .[dev]
          pip install mypy
          pip install types-setuptools

      - name: Run MyPy check
        run: 
          python3 -m mypy src/oakutils --config-file=pyproject.toml
